### ISSUE TITLE
Copy won't re-copy files if they are missing on the remote server

### ISSUE THREAD

**Issue by allanhaywood** [Microsoft/VSLinux#100]
* A brief description
When the projects directory on the remote server is removed, the copy stage of the remote build doesn't re-copy files that have been removed from the remote server.

* Expected results
If files are missing from the remote server, they should be re-copied again, even if they haven't changed locally.

* Actual results (with build output window contents if applicable)
Only files that have changed locally will be copied.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
This occurs in both VS Community 2015 and 2017

* Steps required to reproduce the error
Setup and get a Linux project working on a remote server. 
Rename or delete the project folder on the remote server.
Re-run copy/compile/execute from VS
Files missing on the remote server are not re-copied.

* Required packages and commands to install
NA

NOTE: It would also be good if it was detected when the remote files were changed, and prompt for desired action (ex. force copy to remote, copy from remote to local machine, do diff, merge, etc)

**Comment by allanhaywood** [comment]
This has been open for almost a month with no comment, is there a proper way to ask this to be reviewed soon?

**Comment by stanthomas** [comment]
`Rebuild` will cause all files to be copied over whether changed or not.

If files are deleted on the remote outside VCLinux control then surely the same process should delete them on the Windows host too :)
I would argue that you have a contract with VCLinux that the files it copies to the remote remain where it put them. This allows incremental builds to proceed with a minimum of overhead. If VCLinux is to check for the presence of files on the remote that it put there then when should this check take place? It does the copy, then it does the compilation. If the remote is removing files then presumably they could go AWOL between the copy and compile steps. `Rebuid` seems the only option.l

As for why MS are rather quiet, I'd guess they're all beavering away on the VS2017 release. But you could try nudging Marc Goodner on twitter (@robotdad) if you're feeling neglected.

**Comment by allanhaywood** [comment]
Good to know rebuild will re-copy all files. I'll try that out.

**Comment by allanhaywood** [comment]
Rebuild did what I needed. Closing.

**Comment by renzoll** [comment]
I'm currently experiencing this same issue with a Makefile project in VS2017 Enterprise with Visual C++ for Linux Development 1.0.6, and unfortunately rebuild is still failing to copy files:

1>------ Rebuild All started: Project: ProtobufDefinitionsLinux, Configuration: Debug x64 ------
1>Build started 4/20/2017 9:42:41 AM.
1>  Validating architecture
1>  Current project architecture 'x64' is compatible with the remote system architecture 'x64' ('x64').
1>Target _ValidateSources:
1>  Validating sources
1>Target _CopySources:
1>  Copying sources remotely
1>  Skipping '..\Makefile', as it is up to date.
1>  Skipping '..\data.proto', as it is up to date.
1>  Skipping '..\service.proto', as it is up to date.
etc

I'm guessing it's probably related to a different project configuration issue since this is a test attempt at creating a protobuf compilation project on a remote linux machine. Any idea why rebuild is not forcing the sources copy in this case?

**Comment by rosenqui** [comment]
I had the same issue - nothing would get copied unless you modified the local file. I'm building on a Docker image that comes up fresh each time. VC thinks it has already copied the files so it doesn't do anything.

The workaround is to delete the local 'obj' folder where files whose names end with `CopySourceUpToDateFile.tlog` live. For my project that's obj\x64\{Debug|Release}. That seems to be where VC keeps track of what it copied to the remote system and when.
