### ISSUE TITLE
shellexec hangs, gdb fails to launch

### ISSUE THREAD

**Issue by jwt27** [Microsoft/VSLinux#107]
* A brief description
I am trying to use this extension to build a project using a cross-compiler installed in MSYS2 (mingw64). I have sshd set up running locally under MSYS2 and Visual Studio properly connects to it. The "remote" build process succeeds, but gdb fails to launch.

* Expected results
After pressing F5, Visual Studio should connect over ssh, and launch gdb.

* Actual results (with build output window contents if applicable)
After building the project, Visual Studio appears to hang. In task manager, `shellexec.exe` is using 100% cpu time. After terminating this process, Visual Studio resumes (albeit with the obvious error message).  
Manually entering the shellexec command (found in the Debug Output window) with the `/diag` switch results in the following output:  
`C:\Windows\System32>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\Linux\Linux\\shellexec.exe" /s -616725650 /diag /c gdb --interpreter=mi`
`shellexec 1.0`
`Copyright (C) 2016 Microsoft Corporation. All rights reserved.`
` `
`Connecting...`
`Connected to remote system!`
`^C`  
After saying it's connected to the remote system, it hangs indefinitely until I press Ctrl-C.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc.
VS Community 2015, GCC version 6.3.0, GDB version 7.12.1, build arch amd64, target arch i386

* Steps required to reproduce the error
Set up a project with gdb remote debugging. Press F5.

* Required packages and commands to install
Not sure if these are required, but I'm using MSYS2, with sshd set up using the following script: https://gist.github.com/samhocevar/00eec26d9e9988d080ac

**Comment by robotdad** [comment]
So it looks like you've figured out a way to use the Linux project system with MinGW. That isn't something we've tried, nor is it something we are looking to support in this way. Since you reported this there has been work in other areas that you can use MinGW with Visual Studio. I suggest you take a look at this post on [using MinGW and Cygwin with open folder](https://blogs.msdn.microsoft.com/vcblog/2017/07/19/using-mingw-and-cygwin-with-visual-cpp-and-open-folder/).
