### ISSUE TITLE
File paths are not kept when copying

### ISSUE THREAD

**Issue by allanhaywood** [Microsoft/VSLinux#108]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
I have a simple project with two files, a Makefile, and main.cpp.
Makefile is in the root of the project folder, and main.cpp is under src.

ex, root of project folder:
src/main.cpp
Makefile

However, when the Copy Sources, copies the files remotely, it puts them both at the root of the project folder.

ex:
main.cpp
Makefile

One thing worth noting, is that I have another Linux c++ project, and it is working as expected. It is a larger project with source files under both src/ and test/ and the folder structure is maintained when copying to the remote server. I'm not sure what is different between the two projects.

* Expected results

Folder structure is the same on both the local and remote machine.

* Actual results (with build output window contents if applicable)

Everything is being copied into the root of the project folder on the remote machine.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Visual Studio:/15.0.0-RC.4+26206.0
VC++ for Linux: 1.0.6

* Steps required to reproduce the error

Create a project that has sub folders in the project directory with sources in them.
Execute Remote build and the files all end up in the root of the project folder.

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by olivier-haddad** [comment]
I had the same issue in previous versions but it was fixed in 1.0.6.
The following may influence the folder hierarchy in the linux machine:
-your project includes files from folder external to the PC project root. For instance, if you have an external "common" or "include" folder.
-your project references a visual studio "shared project".

However, as I said previously both cases have been fixed. In the case of external included files, the extension takes the containing folder as root so your relative path includes still work on the Linux target.

If your project includes files on another drive, I guess it will still be an issue.

Could you provide the PC original file hierarchy and the resulting one on Linux?

**Comment by allanhaywood** [comment]
I haven't seen this on any new projects since this one mentioned here.
I'll dig into the settings on the project with the issue and see if I notice anything different.

**Comment by brettadams53** [comment]
************************************
Linux C++ Projects 
************************************
In test case 1-4 I'm creating single project makefile solutions.  The only change I make to the config
besides the credential info is to change the base location of where I want the remote file
structure to push to. I also merely add filter mapping to match my file structure on disk.

It should be noted I am removing the remote target folder each time so a fresh push of all files should
be produced.

The copy sources tab has:

"Sources To Copy"  	@(SourcesToCopyRemotely)
"Copy Sources"		Yes

************************************
Test 1a: 
************************************
I add a Linux make file project called MakefileProj with the following structure and I add some filters
to contain my source files.  Notice that I only add a single proj1 folder that contains the .cpp file.

[MakefileProj]
	MakefileProj
	MakefileProj.sln
	MakefileProj.vcxproj
	MakefileProj.vcxproj.filters
	MakefileProj.vcxproj.user
	proj1
		main.cpp

On my linux VM, after a build solution the file structure ends up with only the single .cpp file in the
root folder to the project.  The src, zproj and proj1 folders are not maintained.

[MakefileProj]
	main.cpp

************************************
Test 1b: 
************************************
If I then add the proj2 folder with a main.cpp to the project and then do a rebuild soution then the
following structure is created.  The proj1 folder is not maintained as expected but the proj2 is
created as expected.

[MakefileProj]
	proj2
		main.cpp

************************************
Test 1c: 
************************************
I then perform a second build solution and the structure ends up with:

[MakefileProj]
	proj1
		main.cpp
	proj2
		main.cpp

In this case with source files only one level down folders off the project root the outcome on the
remote machine is how I would expect it (matching what I have on my local machine).


************************************
Test 2a: 
************************************
I add a Linux make file project called MakefileProj with the following structure and I add some filters
to contain my source files.  Notice that I only add a single proj1 folder that contains the .cpp file.

[MakefileProj]
	MakefileProj
	MakefileProj.sln
	MakefileProj.vcxproj
	MakefileProj.vcxproj.filters
	MakefileProj.vcxproj.user
	src
		zproj
			proj1
				main.cpp


On my linux VM, after a build solution the file structure ends up with only the single .cpp file in the
root folder.d to the project.  The src, zproj and proj1 folders are not maintained.

[MakefileProj]
	main.cpp


************************************
Test 2b:
************************************
If I then add the proj2 folder with a main.cpp to the project and then rebuild the soution then the
following structure is created.  The src and zproj folders are not maintained

[MakefileProj]
	proj1
		main.cpp
	proj2	
		main.cpp


************************************
Test 3:
************************************
I add a Linux make file project called MakefileProj with the following structure and I add some filters to contain my source files. I add multiple .cpp files from multiple folders this time before I ever do
a build solution on the project.  The results are the same as Test 1b and 2b results.  There is something about having more than one file to push that changes the structure outcome.

[MakefileProj]
	MakefileProj
	MakefileProj.sln
	MakefileProj.vcxproj
	MakefileProj.vcxproj.filters
	MakefileProj.vcxproj.user
	src
		zproj
			proj1
				main.cpp
			proj2
				main.cpp
			proj3
				main.cpp


On my linux VM, after a build solution the file structure ends up with only the parent folders of the .cpp files
added to the project along with the .cpp files.  The src and zproj folders are not maintained.

[MakefileProj]
	proj1
		main.cpp
	proj2	
		main.cpp
	proj3
		main.cpp


************************************
Test 4a:
************************************
I add a Linux make file project called MakefileProj with the following structure under a folder called
Product1 and I add some filters to contain my source file.  This time though I purposely have the source outside the root project
folder outside the root project folder.

[Product1]
	[MakefileProj]
		MakefileProj
		MakefileProj.sln
		MakefileProj.vcxproj
		MakefileProj.vcxproj.filters
		MakefileProj.vcxproj.user
	proj1
		main.cpp


On my linux VM, after a build solution the file structure ends up with only the single .cpp file in the
root folder to the project.  The proj1 folder is not not maintained just like in Test 1a.

[MakefileProj]
	main.cpp

************************************
Test 4b:
************************************
I add another file to the proj1 folder called foo.cpp and perform a rebuild of the solution with the
output created being:

[MakefileProj]
	foo.cpp

Unless I run a rescan solution on the MakefileProj project, the original main.cpp will not be pushed
to the remote.  Regardless the proj1 folder that contained both .cpp files is not maintained.  I suspect that
if I add another folder with some .cpp files in them that the parent to the .cpp files in both folders would
be correct since they are only e level deep.

[MakefileProj]
	foo.cpp
	main.cpp


************************************
Test 5:
************************************
So adding additional source folders beyond a single layer also produced results of not all the parent
folders being maintained across the push.  I'm merely trying to keep the same file structure that
I have locally on the remote machine and use copy sources logic to get them pushed from within vs2017.

************************************
Test 6:
************************************
I tried to remove the @(SourcesToCopyRemotely) and instead do the additional sources to copy folders
directly but this only worked if the source files were in folder relative to the project root folder.
If the source files were outside this folder (as mentioned in another post) then I would get sporadic
behavor such as no files at all being copied or only some of the files.   Just trying to use the additional copy sources commands to push folders using the local:=remote mappings proved to not give me what
I expected.  Am I just assuming too much from this source copy feature and if so what the rules to follow
to what can we expect?

I'm assuming that most Linux projects will not have all the sources under a VS2017 Linux C++ root folder
but instead be a folder structure that the Linux C++ build mechanism is built around.
I have several large projects like this that have folder structures that transcend more than one level and
are not relative to the vs2017 project files meant to control pushing and building. Using vs2015 and putty with
custom copy commands I could do what I wanted.  I had hoped that vs2017 could remove some of those
external tools needed to make this work but from my testing it's not giving me what I want.  I suppose
I can just use custom build commands to get my copying done how I want and use the project to execute 
my cmake build as I have done for a while.

These problems are claimed to be fixed and working for others with 1.06 of the extension but that is what
I'm using.
VisualStudio/15.0.0-RTW+26228.4
Visual C++ for Linux Development 1.0.6

I haven't tested out having multiple projects in the solution and having files under there to see if that changes anything.  If that is the only way the copy sources is designed to work then that means my projects are dependent on a folder structure dictated by vs2017.   Hopefully I'm not the only one having problems with thus stuff and can get back some helpful tidbits.

**Comment by brettadams53** [comment]
Well, the structure was formatted ok when I pasted it in.  The result was just flattened, making it hard to read. Ugh!  Maybe it's still enough information to go on.

**Comment by AliAskari** [comment]
I also have the same issue on Visual Studio 2017. The project structure is not respected when it's copied over.

**Comment by hvbommel** [comment]
same problem here. I use visual studio 2017 also. brettadams53 is not the only one. It is very annoying and cost me a day because it was hard to believe there is no proper solution (as far as id I know)

**Comment by hvbommel** [comment]
But thanks to brettadams53 for reporting this ! I will start using pscp to work around for the time being.

**Comment by Izowiuz** [comment]
No proper solutions as of yet? Not sure how I'm suppose to compile my project when it has multi-folder structure. This almost seems like I missed something in the settings of visual studio.

For the record, I'm using vs2017 15.5.5 and VC++ for Linux Deployment 1.0.8

**Comment by Izowiuz** [comment]
It was my fault, everything works now. It seems I had messed up project / solution relations when I was moving files by hand.
