### ISSUE TITLE
Using VSLinux with Nvidia DRIVE PX

### ISSUE THREAD

**Issue by Fladenbrot** [microsoft/VSLinux#125]
Hi all,

I'm working with a DRIVE PX (1) from Nvidia, where I firstly want to debug C++ code remotely using Visual Studio. I created an Visual C++/Cross Platform/Linux/Console Application (Linux) and changed the platform to "ARM" in the solution property window. The remote system is detected as "Ubuntu (Unknown)".

So when I want to debug a simple code, I get the error "Current project architecture 'ARM' is incompatible with the remote system architecture '' ('Unknown'). Please switch the project architecture to '' in Configuration Manager."

Is there any way to debug the C++ code remotely on the DRIVE PX with Visual Studio?

I've already tried using GDB debug mode instead of gdbserver, but getting the same error.

I'm using Visual Studio 2015 as well as 2017 with Visual C++ for Linux Development 1.0.6. The Linux on the Nvidia DRIVE PX is an Ubuntu 15.04 (GNU/Linux 3.18.19-tegra aarch64) with an Tegra 210/X1 System (ARMv8 ). The GDB is a GNU gdb (Ubuntu 7.9-1ubuntu1) 7.9.

I hope that's all what you need to help me, unfortunately I'm not that big linux geek.

Thank you in advice.

Steve

**Comment by stanthomas** [comment]
Issue #110 might have some suggestions you can use.

**Comment by itodirel** [comment]
We don't currently support ARM64

**Comment by itodirel** [comment]
we added support for ARM64 a while back, let me know if it works for you now

**Comment by itodirel** [comment]
This has been addressed. Please let us know if you have further issues, please open a issue for us or a suggestion on the Developer Community. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
