### ISSUE TITLE
Can not include #include <sys/io.h> <sys/sysinfo.h> <sys/stat.h> <unistd> etc.

### ISSUE THREAD

**Issue by JethroLin** [Microsoft/VSLinux#127]
Hi,
When i used the headers as tile, the IDE give me error: can not open source file "*.h".

I can't find these header files in my vc dierectory, where is "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Linux\include\usr\include\x86_64-linux-gnu\sys".

Where i can find these files? I'll appreciate that.

**Comment by stanthomas** [comment]
It seems not all headers are installed by VCLinux. Copying them from your Linux system should fix your problem. See: http://stackoverflow.com/questions/43022494/linux-header-file-not-recognized-in-visual-studio-2017-linux-project/43034796#43034796 .

Since there are subtle differences in which headers are present and where they are located on different Linux systems it might help the VCLinux team if you document your Linux system and the missing headers with their paths.

**Comment by itodirel** [comment]
Automatically copying headers and providing good IntelliSense beyond the C++/C standard libraries is something that we know that we absolutely need to improve. But it's a bit of work, we have it planned in the near future so I'm going to tag it with _feature_. In mean time, you can copy those headers locally and point IntelliSense to them, that should work as a temporary work around.

**Comment by itodirel** [comment]
Using #43 for tracking

**Comment by itodirel** [comment]
As an update, we implemented this feature
