### ISSUE TITLE
Support project to project references, and library templates

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#13]
More complex solutions need support to reference other projects.

**Comment by markfinal** [comment]
(Tested in v1.0.4)

After some digging around in VS diagnostic build output, I found these properties:

```
1>                   RemoteProjectDir = ~/projects/Library
1>                   RemoteRootDir = ~/projects
```

So I was thinking I could use these in AdditionalIncludeDirectories, for both the current project, and for dependent projects.

So with this source code structure for a project

```
Library/include/*.h
Library/source/*.c
```

I set this as the include search path:

`$(RemoteProjectDir)/include`

But this failed to compile, because the command line to compile a source file was (according to VS diagnostic output)

`1>                                     CommandLine=-c -x c /home/mark/projects/Library/source/library.c -I "/home/mark/projects/Library/~/projects/Library/include" -g1 -o "/home/mark/projects/Library/obj/x64/Debug/source/library.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-pointer-sign" -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O3 -fno-strict-aliasing -fomit-frame-pointer -DNDEBUG -fthreadsafe-statics -fexceptions -frtti -std=c11`

Note the include search path: there is an assumption that all additional include dirs are relative to the project directory on the Linux box, i.e.

`/home/mark/projects/Library/~/projects/Library/include
`


Suggestion:
if AdditionalIncludePaths are absolute (or start with ~), do not append them to the project root on Linux, just treat them verbatim.

**Comment by robotdad** [comment]
This is fixed in VS 2017 15.3

**Comment by yosoymin** [comment]
I'm having issues using project references in Linux projects. I have 2 projects, one executable (.out) depending on another library (.a) project, but I can see a warrning icon in the reference of my executable project to the library. If I see the properties of the reference, there is a message in the Full Path field that says: "The "Microsoft.VisualStudio.ProjectSystem.References.UnresolvedBuildDependencyProjectReference" reference could not be resolved."

I't seems that the executable project can't find the library output .a directory. Both projects are using default properties for everything except for VC++ Directories->Include Directories.

I'm using Visual Studio 2017 Community 15.3.1

**Comment by levhaikin** [comment]
@yosoymin ,
have you solved the `Microsoft.VisualStudio.ProjectSystem.References.UnresolvedBuildDependencyProjectReference`
issue?
