### ISSUE TITLE
Autocomplete on Qt types (bug)

### ISSUE THREAD

**Issue by opensw** [microsoft/VSLinux#136]
Hello there,
   I have set "Include Search Path" and "Forced Includes" to Qt include paths.

If I write something like following

```
#include <qstring.h>

int main(int argc, char* argv[])
{
    QString str = "Hello world";
}
```

then I do not have autocomplete on str variable (I mean when I type str.) but "Peak Definition/Go To Definition" on QString is working and "Open Document" on qstring.h too.

Is there a workaround to fix this?

Host: Windows 10
Guest: Hyper-V Ubuntu 16.04
Visual Studio: 2017
Qt: 5.4 and 5.8

**Comment by robotdad** [comment]
The QT include paths you set are local on the Windows machine?

**Comment by itodirel** [comment]
it compiles and runs, but there seems to be some IntelliSense issues

**Comment by itodirel** [comment]
We are successfully using and targeting Qt, with no issues, on latest updates of VS. We believe we have addressed and fix this issue. You have to specify /usr/include/x86_64-linux-gnu/qt5 in the additional include directories in the Property Pages, you can also specify /usr/include/x86_64-linux-gnu/qt5/QtCore if you wish to simply include <QString>, if you are experiencing further issues, please open a issue for us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
