### ISSUE TITLE
Build task Id 50 'Copying file' with mapped sources on WSL breaks executable

### ISSUE THREAD

**Issue by fuocor** [microsoft/VSLinux#138]
* A brief description
After running into problems copying source (see: [shared items problem](https://github.com/Microsoft/VSLinux/issues/137)) I set 'Copy Sources': No and set 'Remote Build Root Directory': /mnt/c/ossiaco/nanogrid/projects/linux/tests/json, which corresponds to the Windows directory.

The build and link tasks completed successfully, but running the app (catch unit tests), the program simply exits.

If I relink the project output from bash, then the app runs fine

* Expected results
Program output
`All tests passed (127 assertions in 13 test cases)`

* Actual results (with build output window contents if applicable)
Nothing

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Windows 10 Creators update
VS 2017 15.1
Visual C++ for Linux Development 1.06

[test_basic_json.log.txt](https://github.com/Microsoft/VSLinux/files/966842/test_basic_json.log.txt)

**Comment by itodirel** [comment]
I believe the error happened due a misconfiguration in the project. We have added native support since, which we recommend using with WSL instead of SSH to WSL. If this is still a issue for you, please open a issue on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
