### ISSUE TITLE
Connection manager hangs when extra text is displayed at login (tcsh)

### ISSUE THREAD

**Issue by IntoCpp** [microsoft/VSLinux#147]
* A brief description
The connection manager hangs if the SSH login contains extra lines.
May be related to item #28 (Incompatible with other shells than sh/bash)
 
* Expected results
The connection should be established; or at least an error message be reported after a time-out.

* Actual results (with build output window contents if applicable)
The connection manager just stay's there with no feedback; after several minutes 'devenv' must be manually killed.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Visual Studio Community 2017 - 15.2 (26430.6) + .NET 4.6
Visual C++ for Linux Development 1.0.6

Target: CentOS 6.7

* Steps required to reproduce the error
1) On the remote Linux machine, edit your “.cshrc” (or equivalent) to display (echo) a custom line right after the login. 
For example, last few lines of my .cshrc:

`     set prompt="%B%{\033[34m%}%P %{\033[31m%}[%n] %{\033[33m%}[%~]\n%{\033[30m%}%b"`
`     # Fetch the IP address for this system`
`     set IPETHZ = `/sbin/ifconfig eth0 | awk -F ' *|:' '/inet addr/{print $4}'``
`     echo "My IP is '$IPETHZ'”`

2) From Visual Studio, create any Linux project.
3) Menu: Tools | Options | Cross-Platform | Connection Manager
4) Enter IP and credential to the Linux system and press “Connect”
At this point nothing happens;  I end up killing ‘devenv’ after waiting several minutes.
Removing the line: echo "My IP is '$IPETHZ'” and everything works fine.

Some system requires legal text to be displayed, so removing is not always an option.

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by ascl00** [comment]
I hit this issue as well. The complete lack of feedback makes troubleshooting difficult! Note that I hit this using bash, so the issue is not limited to shells other than sh/bash.

Very easy to reproduce, I simply had an 'echo stuff' statement in my .bashrc.

**Comment by itodirel** [comment]
labeled as a bug, we will investigate and fix

**Comment by itodirel** [comment]
It sounds like you have a workaround. Thank you, tracked with, and planned to be addressed, in our roadmap: https://developercommunity.visualstudio.com/idea/956725/compatibility-with-other-shells.html

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Comment by itodirel** [comment]
This is now fixed
