### ISSUE TITLE
Debugger confused with c++ files having the same file name under different folders

### ISSUE THREAD

**Issue by super-kevin** [Microsoft/VSLinux#149]
* A brief description
If there are more than one c++ files having the same file name under different folders, setting breakpoint (gdb backend) in one of them may affect others. Other debug function related to these files also have strange behavior.

* Expected results
Debugger can tell the difference between these files.

* Actual results (with build output window contents if applicable)
Debugger treat these files as the same ones. Many functions have strange behavior.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
VS 2017 15.2 (26430.12); Debian 8.8; GNU gdb (Debian 7.11.1-2~bpo8+1) 7.11.1; x64.
It is a normal Linux install in a virtual machine.

* Steps required to reproduce the error
Attach to a running process (gdb backend).
Set break point by left click on the beginning of a code line.
Another file with the same file name may be affected by this action and it seems that the break point I just set was also applied to this file. And the editor may show the wrong file when the program hit the breakpoint.

* Required packages and commands to install
A "hello world" program with two or more files have the same name is enough.

BTW, vscode has the same issue: https://github.com/Microsoft/vscode-cpptools/issues/692
Demo on that page: https://github.com/Microsoft/vscode-cpptools/files/989448/bp_bug_demo.zip

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by paulmaybee** [comment]
The fix for this issue is in VS2017 version 15.3. You can find a preview of this release at https://www.visualstudio.com/vs/preview/
If both source files are in the project being debugged then no change is required. However if one of the files in in a path outside of your project then you will need to describe its mapping to the debugger using the new project property "Properties->Debugging->Additional Source File Path Map". For example, "c:\users\me\mysource\=/home/me/mysource/" will establish a mapping between files on a windows machine (c:\users\me\mysource\) and same files when compiled on a Linux machine (/home/me/mysource/). The debugger will then have a complete path name for the file and should distinguish between two files of the same base name.

**Comment by robotdad** [comment]
@super-kevin 15.3 has the fix for this and is released now. Please let us know if you see this again.
