### ISSUE TITLE
-lmysqlclient , collect2 : error : ld returned 1 exit status

### ISSUE THREAD

**Issue by htdw** [Microsoft/VSLinux#153]
1>Copying sources remotely to '192.168.149.130'
1>Starting remote build
1>Compiling sources:
1>main.cpp
1>Linking objects
1>collect2 : error : ld returned 1 exit status

Ubuntu 16.04
Add -lmysqlclient
What is wrong with this solution?

PuTTY enter “g++ -Wall main.cpp -o main -lmysqlclient“ Can be successful.

**Comment by aygkhn** [comment]
i have same problem. you are writing putty not like visual studio. visual studio creates g++ parameters like this: “g++ -Wall -lmysqlclient“ main.cpp -o main". but i cant understand why this is not work.

**Comment by SamuelHenderson** [comment]
Hi!  I ran into a similar problem when trying to link against SDL2.  I had my 'Library Dependencies' in Project Settings->Linker->Input set to:
`-lSDL2;-lSDL2_image;-lSDL2_mixer;-lSDL2_net;-lSDL2_ttf`

Visual Studio adds the '-l' automatically apparently so changing the dependencies to:
`SDL2;SDL2_image;SDL2_mixer;SDL2_net;SDL2_ttf`
Allowed the linking to complete.

Another thing to check is that the 'Project Settings->Linker->General->Shared Library Search Path' and 'Project Settings->Linker->General->Additional Library Directories' have the path to wherever this 'mysqlclient' shared object library is on your remote machine.  In my case I had to add `/usr/lib64;` to these two settings.

**Comment by itodirel** [comment]
Can you get me the command line that works, and the one that doesn't from the build ouput, and we can help you configure it correctly. 

You have the following options here:

Linker - General - Additional Library Directories - this adds paths with -L to the linker command line near the beginning of the command line.
Linker - Input - Library Dependencies - this adds the file names with -l at the very end of the linker command line
Linker - Input - Additional Dependencies - this adds the entries verbatim after the object files, and before the Linker - Input - Library Dependencies
Linker - Command Line - Additional Options - this adds the entries verbatim before the object files in the linker command line

**Comment by itodirel** [comment]
Closing the issue due to inactivity, if this is still a problem, please reactive and we can further explore and investigate the issue.

**Comment by vikaschamp** [comment]
I am facing same issue . I have set remote library path and library name in visual studio .
Still it's not finding library while building the project .
![image](https://user-images.githubusercontent.com/9655086/101654537-a983e280-3a66-11eb-9432-70c212bada2d.png)

**Comment by hirdeepThor** [comment]
Just a comment about specific use case: "~" symbol for home directory is not expanded properly under the Project->Configuration Properties-> Linker ->General -> Additional Library Directories.

Please see the following images for Configuration properties for  Header Include directories and Linker Additional Library Directories 

![image](https://user-images.githubusercontent.com/112515060/187543541-54fca527-f52e-4498-81fc-1c3258675c30.png)

![image](https://user-images.githubusercontent.com/112515060/187543610-98a3fd14-2406-495b-bf0a-dfd3b85a34b8.png)

I get following output:
![image](https://user-images.githubusercontent.com/112515060/187543843-afba6827-bfc0-4dc0-b37f-4483e831aa41.png)
Please notice the difference between -I and -L argument difference.

Since ~ was not resolved correctly I got the cannot find the file problem.

If I mention the path explicitly in Additional Library Directories and adding library name without -l or lib prefix and without .so or .a suffix I was able to compile the code. See below:

![image](https://user-images.githubusercontent.com/112515060/187544721-5acc0423-2682-41f9-a73f-be4a44ccee71.png)

![image](https://user-images.githubusercontent.com/112515060/187544769-5b369090-fd4c-41f7-a539-035178c1d1bd.png)

Output result:
![image](https://user-images.githubusercontent.com/112515060/187545352-a988ac56-a7c8-41d8-9791-7a6ac5e5b759.png)
