### ISSUE TITLE
how to change a VC++2005 project to a Ubuntu project?

### ISSUE THREAD

**Issue by neotim** [Microsoft/VSLinux#154]
please give some suggest.

**Comment by stanthomas** [comment]
You could make a start by moving to Visual Studio 2017.

**Comment by itodirel** [comment]
The simples way is to change the ApplicationType and ApplicationTypeRevision to Linux like this (in your vcxproj file):

 <ApplicationType>Linux</ApplicationType>
 <ApplicationTypeRevision>1.0</ApplicationTypeRevision>

But you'll likely need more changes, depending on how your project is structured. If it's possible for you to get us access to your project, we can tell you specifics. Otherwise, there is no simple answer.

**Comment by robotdad** [comment]
Let us know if you need any more help on this
