### ISSUE TITLE
Add support for child process debugging

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#16]
The MIEngine supports this, we just need to add a flag in the project properties that enables it if needed.

**Comment by Performer777** [comment]
I would suggest to reformulate goal as add support for debugging process tree with possibility to configure exclusions and inclusions of processes outside of the main process tree. Very useful for some IoT/server scenarios. The problem which this feature would lies in frequent usage of processes instead of threads in several linux workhorses i.e. apache httpd.
