### ISSUE TITLE
Extension Settings tool window options in the IDE's debugging view are ignored

### ISSUE THREAD

**Issue by dpodder** [microsoft/VSLinux#166]
When debugging a Linux binary over SSH using Visual Studio C++/Linux integration, the "Exception Settings" tool is accessible and lets you toggle settings to automatically break on certain kinds of C++ exceptions. Regardless of what's selected, however, the settings are ignored; C++ exceptions don't trigger any breakpoints.

![image](https://user-images.githubusercontent.com/2354388/28851205-e8d8429e-76d5-11e7-97f4-76f9a09048e1.png)

### Simple repro
```C++
#include <exception>
#include <iostream>
int main(int argc, char **argv)
{
    try {
        throw std::exception();
    }
    catch (const std::exception &e) {
        std::cout << "Caught an exception" << std::endl;
    }
    return 0;
}
```

### Expected results
The debugger should break on the `throw` statement

### Actual results
Program execution continues to the end of main without breaking.
When compiled for Windows x64 and debugging locally, with the same configuration, the program breaks on `throw`.

### Version information
* VC++: 15.3.0 Preview 7.0 [26730.0.d15rel]
* Linux system: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64)
* GCC: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
* GDB: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
* gdbserver: GNU gdbserver (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
* CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (hardware; not a VM)

**Comment by itodirel** [comment]
we don't currently support the Exceptions window, @paulmaybee any ideas what it would take for that to work and whether gdb supports it?

**Comment by pieandcakes** [comment]
this is possible with gdb catchpoints. https://sourceware.org/gdb/onlinedocs/gdb/Set-Catchpoints.html#Set-Catchpoints . It doesn't look like there is a good way to do this through MI though.

**Comment by pieandcakes** [comment]
created an issue at: https://github.com/Microsoft/MIEngine/issues/644

**Comment by itodirel** [comment]
@paulmaybee is this something that works now?

**Comment by itodirel** [comment]
We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
