### ISSUE TITLE
"Clean" of CMake Project on Linux in VS Preview 15.4

### ISSUE THREAD

**Issue by UB909** [Microsoft/VSLinux#179]
There is no possibility to perform a clean build on the target machine. For a clean build I would expect that the build directory on the target machine is flushed, and all source files are copied to the target machine again. The only way to force a clean build is to delete the folders in /var/tmp/build and /var/tmp/src, close visual studio, delete the .vs folder and restart visual studio again. If you don’t restart visual studio you will get an error that the directory is missing.

The feature itself is necessary if you are using different build machines in one project and switch the build machine by changing the IP address in the configuration in CMakeSettings.json. If you do this the files on the new build machine are not updated.

**Comment by lukka** [comment]
@UB909 currently you could right click on the CMakeLists.txt file on the solution explorer, then select Clean All menu option. Then the remote directory /var/tmp/build/abcdef1234078 is wiped out, and CMake regeneration need to be manually triggered again. 

Feedback about this awkward procedure is welcome in order to provide a better experience.
