### ISSUE TITLE
Add a new entry to the CMakeSettings.json for remoteDebugMachine

### ISSUE THREAD

**Issue by AliAskari** [Microsoft/VSLinux#191]
I have not been able to test the new CMake integration in update 15.4 but I see one big problem that will not let us update to this version. 

With the VS project files we can add new configurations and add a different debug machine #87 .Doing so would allow us to [build on machine A and then debug it on machine B](https://github.com/Microsoft/VSLinux/issues/109). I don't see how we can have this option with the new CMake integration. 

It would be really amazing to have the option of specifying both build and debug machines under one single configuration in CMakeSettings.json in a format like this:

      {
            ...
            "generator": "Unix Makefiles",
            "remoteBuildMachine": "build@192.168.10.10",
            "remoteDebugMachine": "debug@192.168.10.11",
            "configurationType": "Debug",
            ...
      }

also it would be much better to explicitly specify the machine, `username@ip.address`. At least in our workflow we source control this `CMakeSettings.json` file and if the remote machines are not specified explicitly there is a risk of having different build outputs on different work stations.

**Comment by paulmaybee** [comment]
You can set different remote machine for build and debug. In your CMakeSetting.json set your remoteMachineName to your build machine and in your launch.vs.json set the remoteMachineName to your debug machine. If you right click on a CMakeLists.txt file you will see an option for "Debug and Launch Settings". Selecting this for one of your targets will let you customize the launch options. 
Notice that after you do this (because of a product bug) there will be a duplicate name for your target added to the target selection menu in the toolbar at the top. So you will have to select the new entry (first in the list) to debug with your new options.
