### ISSUE TITLE
Installation - Documentation

### ISSUE THREAD

**Issue by acepace** [microsoft/VSLinux#207]
The blog post documentation is not up to date.
https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/

Should not say Linux development with C++, since that's not the name. but Visual C++ for Linux Development

**Comment by robotdad** [comment]
Thanks. That post is due for an overhaul I haven't had time for yet. The reason for why it is named that way is because when we integrated into the VS installer that was the name we used.
![image](https://user-images.githubusercontent.com/1429895/32281947-8ad18804-bedd-11e7-83db-79af63dfd247.png)
We should probably update the title of the blog to reflect that.

**Comment by itodirel** [comment]
@esweet431 can you drive this?

**Comment by itodirel** [comment]
We don't typically update blog posts once we have posted them. We do however make new blog posts with updated documentation, as well as maintaining docs.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
