### ISSUE TITLE
[ CMake ] Cannot view compiler errors in error window or double click on errors in output window

### ISSUE THREAD

**Issue by iwubcode** [microsoft/VSLinux#225]
**A brief description**

Cannot view errors in error window.  Cannot double click on error in output window and be taken to file with issue.

**Expected results**

Able to see compiler errors in the error Window.  Able to interact with them in the output window (take me to the actual file that had an error).

**Actual results**

The output is displayed in the output window but is not interactable.  Nothing in the error window.

**Environment**

Visual Studio 2017 15.5 Preview 4
CMake 3.9.0
g++ 4.8.2

**Steps required to reproduce the error**

* Have a CMake Project
* Compile file with error
* View how there is no error in error window and double clicking doesn't take you to the file

**Comment by iwubcode** [comment]
Please let me know if you need me to provide a sample project.

**Comment by itodirel** [comment]
Hi, we think this is currently fixed, but please provide a project to verify or if you think this is not an issue, please close

**Comment by iwubcode** [comment]
Thanks!  I will close for now but will reopen if I see any issues.

**Comment by itodirel** [comment]
We believe this has been fixed quite a while ago in the latest version of VS, please open a issue on the Developer Community if you see any problems here, but we don't expect you to.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
