### ISSUE TITLE
[ CMake ] [ Question ] What does it mean when I see 'Configuration Failed'

### ISSUE THREAD

**Issue by iwubcode** [Microsoft/VSLinux#228]
After running CMake on a new project, I'm seeing 'Configuration Failed'.  What does it mean?

Example:

```
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> Configuration failed.
```

Using Visual Studio 2017 Preview 5

**Comment by lukka** [comment]
@iwubcode  that means some error/exception occurred during CMake output parsing time. 
Could you provide a small reproducible example? Which version of CMake?

**Comment by iwubcode** [comment]
@lukka - I can see if I can reproduce it in a smaller example.  We were using 3.9.0 version of CMake.  Is it possible to just print out the underlying failure instead of 'Configuration failed' or is there not access to that?

**Comment by lukka** [comment]
@iwubcode disregard my previous message, it is not Visual Studio the source of that error. 
The message "Configuration failed." come from [CMake itself](https://github.com/Microsoft/CMake/blob/a69f4e17fbc54d2da07e9ad1b7a29e061347f751/Source/cmServerProtocol.cxx#L1238).
A repro is really needed in order to understand why configuration failed.
By the way, could you please check whether you have any useful information in the CMakeOutput.log or CMakeError.log files?

**Comment by lukka** [comment]
Closing the issue as no repro provided. Please feel free to open a new report on [Developer Community forum](developercommunity.visualstudio.com/
), thanks!
