### ISSUE TITLE
Trying to compile a single file fails

### ISSUE THREAD

**Issue by drrggibbs** [Microsoft/VSLinux#234]
If I right-click on a source file and select Compile (or Ctrl+F7) the compile fails.

The compile command sent to the Linux machine  looks like this:
-c /home/user/projects/VS_Remote_Build/libG/General/Something.cpp -g2 -gdwarf-2 -o "/home/apluser/projects/VS_Remote_Build/libG/obj/x64/Debug/Something.o" ...

There are two issues with this: (1) the compiler name, e.g. g++, has been omitted at the start, and (2) the name of the file to be compiled is always the same, no matter which file I actually select. It appears it is selecting the first source file in the vcxproj file.

Using VS 2015 and VCLinux 1.0.7

**Comment by drrggibbs** [comment]
Retested with VS 2017 (15.5.2) and VC Linux 1.0.8
Behavior is different.
If the source file has not changed, VS says it's up to date and won't try to recompile
If the source file has changed, VS will recompile it correctly, but if I then try to build the project VS unnecessarily recompiles all the other sources.

**Comment by itodirel** [comment]
Regarding 

> but if I then try to build the project VS unnecessarily recompiles all the other sources.

This behavior is by design, single file compile does not know about the overall full build and does not sync the up-to-date-ness. 

Regarding compile not running when the source file is up to date, I believe this is a recent change and we are consistent in doing that with the C++ Desktop experience.
