### ISSUE TITLE
Suggestion: Ability to put source files in a directory not in the Linux build directory

### ISSUE THREAD

**Issue by drrggibbs** [microsoft/VSLinux#237]
I have a setup on a network of Windows and Linux machines. I can map my Linux home directory to a Windows drive. So, I could put my source code in a directory accessible to VS running on my Windows machine, and accessible to Linux for the compile. This would remove the need to copy files from Windows to Linux.

However, VSLinux thinks the source files are in the remote build directory, so doing a clean or rebuild clears the build directory, thus clobbering the source files.

So my suggestion is the option to have the possibility of defining a separate directory, not in the remote build directory, to contain the source.

Using VS 2015 and VSLinux 1.0.7

**Comment by epicabsol** [comment]
This would also be very useful when building via a virtual machine that provides the guest OS access to certain folders in the host filesystem.

**Comment by lukka** [comment]
@drrggibbs Thanks for reporting this. Please could you provide the following information:
   1-  which kind of .vcxproj projects are you using?  Console Application or Makefile based?
   2-   When you say "clobbering the source files" what do you mean exactly?

**Comment by drrggibbs** [comment]
1. I'm using a console application
2. The source files are copied to the Remote Build Project Directory. Doing
a clean or rebuild deletes this directory. When I said "clobbered", I meant
deleted, as in the whole directory is deleted.

**Comment by itodirel** [comment]
Hi, we support copying arbitrary files to arbitrary locations, and they won't be deleted during clean, please let us know if that works for you

**Comment by itodirel** [comment]
to what I was mentioning before, you can disable source copy in Copy Source, and for each source file you can specify its location on the remote machine

**Comment by itodirel** [comment]
Here is how you can do it for on, and then can mechanically automated and generate the rest cia Python script for example @drrggibbs @epicabsol. Lets say your common location for the sources is on Windows (this won't work otherwise), put a header in that location, call it header.h, configure it on the per file Property Pages, to not be copied, and specify where its location is expected on the remote system. 

![image](https://user-images.githubusercontent.com/15239856/77509842-b6a26800-6e2a-11ea-8d08-03d66a563237.png)

In Property Pages for the project, specify the Windows and the Linux Include Directories, as such:

![image](https://user-images.githubusercontent.com/15239856/77509944-efdad800-6e2a-11ea-8245-fd9395bc2887.png)

This tells IntelliSense where the file is to be found by IntelliSense, on Windows. But also configures the build on Linux, such that the #include <header.h> also works in build. 

Makes sense?

I believe this will support your scenario exactly as you suggested it. @esweet431 maybe we can document this in our docs? 

If you have other suggestions, please open a ticket or suggestion for us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
