### ISSUE TITLE
Issues with building a project with different configurations

### ISSUE THREAD

**Issue by drrggibbs** [microsoft/VSLinux#247]
If I have a clean project and build it in both Debug and Release modes there is no problem, except that VS copies the source files again.

If I then clean the Debug configuration, the whole remote project directory is deleted, including all the output for the Release configuration.

If I then select build for the Release configuration, VS thinks Release is still up to date and does nothing.

I think clean/rebuild needs to be more specific than just deleting the whole remote project directory. I think the remote sources shouldn't be deleted when a clean/rebuild is selected for a project. Maybe there should be a "Clean All" option to delete the whole remote project directory including source files.

Using VS 2017 (15.5.2) and Visual C++ Linux 1.0.8

**Comment by itodirel** [comment]
this seems part a bug, that we should fix, and part an optimization that we could make; I'm not sure about cleaning having a different behavior, but maybe we could add a knob for that

**Comment by itodirel** [comment]
The copy should only happen once for each configuration. It needs to happen per configuration as each configuration might have different sets of files, and that is not easily computed. This seems like a nice to have but not a blocker, thank you for your suggestion, we won't be addressing it at this time, please feel free to open a suggestion on the Developer Community and based on demand and votes we can revisit it. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
