### ISSUE TITLE
issue in copy External Dependencies to remote 

### ISSUE THREAD

**Issue by john-yuzhi-zhang** [Microsoft/VSLinux#254]
I created a project (MyTest) using VS 2015 and VSLinux to compile the project in remote Linux machine that has gcc compiler. In the project I have two files: main.c and file_all.c. 

file_all.c contains the following lines
#include "myLocalPath/file1.c"
#include "myLocalPath/file2.c"

In the VS 2015 Solution Explorer, under MyTest (Linux)  project I can see 
file1.c 
file2.c
under External Dependencies (of course there are other files)

In the project configuration Copy Sources tab,  The Copy Sources field is "Yes"

But when do rebuild, only main.c and file_all.c are copied to the remote machine. The file1.c and file2.c
are not copied to the remote machine. And the gcc on remote machine complains file1.c and file2.c do not exist.

Question: How to configure the project to also copy files in External Dependencies to the remote Linux machine? If this is not supported, how can I copy a folder to the remove machine through "Additional Sources to Copy"?

Thanks in advance.

John

**Comment by lukka** [comment]
Please consider using the most up to date version of Visual Studio 2017 instead of Visual Studio 2015, as all our efforts are on Visual Studio 2017.
Regarding your problem, you could:

- add all source files to the solution;
- use a prebuild event command where you copy using rsync or scp the source to the remote machine;
- set Additional Sources to Copy property: each entry is defined as this
      ` c:/file/to/copy/source.cpp:=/home/username/projects/name/directory/source.cpp;....`

Feel free to open the issue again if needed, thanks.
