### ISSUE TITLE
Remote header download issues

### ISSUE THREAD

**Issue by dixonqmg** [microsoft/VSLinux#281]
Two issues with new feature of "downloading linux headers".
1. For some reason it's very slow, I saw 1.8Mbit per second in network monitor, when typically I see about 8mByte per second when scp from the same machine
2. It failed with the following:
vslinux_header_update_log.txt
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must
be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost
)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at liblinux.Services.RemoteCompiler.UnpackSysrootArchiveRemovingDuplicates()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object
_)

**Comment by itodirel** [comment]
Could you tell me what your %localappdata% resolves to? If you can't get us the path, please get us the path length in characters.

**Comment by dixonqmg** [comment]
C:\Users\12345678\AppData\Local

Nothing too long. I suspect it's either a directory structure too deep on a linux side, or some long filename there(this one is unlikely)

**Comment by dixonqmg** [comment]
Longest file name in /usr/include is 69 characters. 
Ah, I think I know what happened there:
-bash-4.1$ find -L /usr/include
find: File system loop detected; `./gphoto2/gphoto2' is part of the same file system loop as `./gphoto2'.
Perhaps you may want to have a better diagnostics for cases like this?

**Comment by dixonqmg** [comment]
Apparently this is how gphoto is installed by redhat, so may be it's a legit way of installing headers? In that case perhaps the way you transverse directories in there should be modified?

**Comment by itodirel** [comment]
thank you for reporting this, we will fix it; can you tell me the distro/version of the distro you're using?

**Comment by itodirel** [comment]
we love all Linuxes, we did some work to use rsync, we'll make sure to check with redhat 6

**Comment by ysiw** [comment]
same issue found for mac host

**Comment by itodirel** [comment]
We believe we addressed all these issues, including OSX, Remote Headers works well with OSX. If this is still a problem for you, please open a issue for us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
