### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jensreck** [microsoft/VSLinux#288]
switching from VS2017 15.6.7 to 15.7.0 (and also 15.8.0 Preview 1.0) a remote CMake project build (x64) failed while CMake run with...

--------------------------

1> Target info extraction done.
1> Object reference not set to an instance of an object.
   at libcmake.CMakeTargetBase`1.SetTargetInfoAndSources[BacktraceProtocol](CMakeTargetJsonProtocol`1 info, CMakeProjectJsonProtocol`1 project, DebugTargetType DebugTargetType, IDictionary`2 traceDictionary)
   at libcmake.Linux.RemoteCMakeProject.GenerateTarget[BacktraceProtocol](CMakeTargetJsonProtocol`1 tgt, CMakeProjectJsonProtocol`1 curProject, DebugTargetType targetType, IDictionary`2 traceMap)
   at libcmake.CMakeProjectBase`3.UpdateListOfTargets[BacktraceProtocol](CMakeProjectJsonProtocol`1 curProject, Dictionary`2 pathToTargetMap, IDictionary`2 traceMap)
   at libcmake.CMakeProjectBase`3.<ExtractInfoGeneric>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ExtractInfo>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()

---------------------------------

  "configurations": [
    {
      "name": "Linux-Debug-x64",
      "generator": "Unix Makefiles",
      "intelliSenseMode": "linux-gcc-x64",
      "configurationType": "Debug",
      "inheritEnvironments": [ "linux-x64" ],
      "cmakeExecutable": "/usr/local/bin/cmake",
      "remoteMachineName": "127.0.0.1",
      "remoteCMakeListsRoot": "/var/tmp/bc8ebb8a-09e5-2b3a-ba8a-df27389fa0e2",
      "remoteBuildRoot": "/var/tmp/bc8ebb8a-09e5-2b3a-ba8a-df27389fa0e2/private/generated/vs2017-Unix_Makefiles/linux-gcc-x64/Debug",
      "remoteInstallRoot": "/var/tmp/bc8ebb8a-09e5-2b3a-ba8a-df27389fa0e2/public/bin/linux-gcc-x64/Debug",
      "remoteCopySources": true,
      "remoteCopySourcesOutputVerbosity": "Diagnostic",
      "remoteCopySourcesConcurrentCopies": "10",
      "remoteCopySourcesMethod": "sftp",
      "cmakeCommandArgs": "-DCMAKE_TOOLCHAIN_FILE=/root/git/DevTools/tool_cmake/addons/modulesX/Platform/linux-gcc-x64.cmake",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "remotePostbuildCommand": "make install"
    }

--------------------------------------------

A CMake run (and make) of synced (VS2017) sources called on remote machine works well.

**Comment by brettadams53** [comment]
I have the same problem except I'm getting it on x86 or 64 bit configurations as well.  I merely upgraded from VS 15.6.7 to 15.7.0 and 15.7.1 with no code changes and this error started happening during the generation phase.  I use a lower version of cmake on my remote Linux VM's (3.9.6 and 3.10) so haven't upgraded them yet.  I suspect that they will have the same problem if I do. The part of my cmake code that ran fine before and now breaks is the add_custom_command() that I use when generating .cc and .h's from google .proto files.   I can also get this error on other parts of my cmake build that are very basic.  I haven't figured those out just yet.

The interesting part is that I can take the exact same source and generate build files with CMake 11.1 external to the VS IDE and it works fine.  So it's something with the internal relationship between the IDE and it's internal CMake 11 that has changed.   Having the ability to pick the cmake that is used for the remote Linux build is nice but for Windows we can't and are forced to either generate outside the IDE or reinstall 15.0 of VS to get around this problem.  Would be nice to roll back to VS 15.6.7 but can't....

Here is my x86-debug run.

1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: C:/Projects/CMakeBuilds/a79e999b-d24e-f832-aa12-4f8d3000b921/build/x86-Debug
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Extracted CTest info.
1> Collating data ...
1> Target info extraction done.
1> Object reference not set to an instance of an object.
   at libcmake.CMakeTargetBase`1.SetTargetInfoAndSources[BacktraceProtocol](CMakeTargetJsonProtocol`1 info, CMakeProjectJsonProtocol`1 project, DebugTargetType DebugTargetType, IDictionary`2 traceDictionary)
   at libcmake.CMakeProject.GenerateTarget[BacktraceProtocol](CMakeTargetJsonProtocol`1 tgt, CMakeProjectJsonProtocol`1 curProject, DebugTargetType targetType, IDictionary`2 traceMap)
   at libcmake.CMakeProjectBase`3.UpdateListOfTargets[BacktraceProtocol](CMakeProjectJsonProtocol`1 curProject, Dictionary`2 pathToTargetMap, IDictionary`2 traceMap)
   at libcmake.CMakeProjectBase`3.<ExtractInfoGeneric>d__94`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.CMakeLists.<ExtractInfo>d__114.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.CMakeLists.<ParseWithoutCacheAsync>d__113.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()

    {
      "name": "x86-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x86" ],
      "buildRoot": "C:\\Projects\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": ""
    },

**Comment by brettadams53** [comment]
Not to just be a bearer of bugs...tried out the new CMake Targets View and must say that is a nice feature when cross compiling and living in the cmake world.   Having additional CMake control is also good to have.

**Comment by lukka** [comment]
@jensreck thanks a lot for reporting this! Could you please provide additional information:
1) which version of cmake is present on the Linux machine?
2) did you compile it yourself? Or is it coming from a standard package of the Linux distribution you are using?
3) are you using WSL? I see 127.0.0.1 as target machine name, it means you are using WSL and you are using SSH to copy file over. Confirm please.
4) are you using root user to connect to the remote Linux machine?
5) what is the content of /root/git/DevTools/tool_cmake/addons/modulesX/Platform/linux-gcc-x64.cmake ?
6) which source files are you compiling? A repro is higly apprecciated!
7) have you tried to build any different project?

**Comment by lukka** [comment]
@brettadams53 thanks for the information!
Please could you provide further information:
1) you report is valid for both Windows and Linux configuration, right? I mean the _configuration_ in CMakeSettings.json file. It seems like you are hitting the same error with a Linux and with a Windows configuration.
2) which project are you compiling? 
3) Is it a systematic error happening on any source code?

**Comment by rchiodo** [comment]
This should be the same issue as this dev community item:
https://developercommunity.visualstudio.com/content/problem/243316/cmake-configuration-fails.html?childToView=248180#comment-248180

There's a workaround, add a line like so to your CMakeLists.txt
add_definitions(-DFOO).

It's a bug in how we parse the definitions for groups of files. If there are more than one group of files with different defines and one of those groups has none, we crash our parsing.

**Comment by brettadams53** [comment]
1. I started with version 3.9.6 I believe when moving over to Open Folder/CMake for Linux.
2. I target various flavors of Linux and since Open Folder is only supported at a certain version of CMake, I simply install a later version on my Linux VM's in their own folder.   I then target that CMake in my .json Linux configuration for make file generation.  Been doing this for a while, it's not perfect but I like it alot better than the old GDBExtension I used before and lots of custom stuff to cross compile on Linux with CMake.
3. I don't target WSL currently as all my remote targets are Linux VM's.   The old way I was targeting CentOS5,6,7,Ubuntu etc.   The Open Folder way with CMake I now setup my remote targets and let VS push all my code so I can compile and debug it remotely.   This lets me do cross compiled code for Windows and Linux using Open Folder and CMake while staying nicely inside the VS IDE.   Been upgrading with VS as things matured and its getting better ever release.   Well until this one which break it on Windows.  Another developer has reported this same problem when using the CMake version 3.11 on Linux with Open Folder.  I suspect the problem is with the linkage between VS and the integrated CMake 3.11 version.   
4. Yes, my remote linkage to my VM's has always been root.  Maybe not the wisest but it works and I can get coding done by ping ponging between the windows config and linux config to make sure my code works as expected on both.
5. I'll have to get back to this.  I'm currently trying to get back to a working 15.0 solution right now so I can verify all of this upgrade path breakage stuff.  I'm going to try the tip by rchiodo, looks like that could be the thing I'm looking for.
6-7. I'm getting breakages on two fronts with 15.7.1.   The first is just trying to compile a small windows application using win32++ headers.  In some cases the project generation will work and in other applications it won't.  I haven't figured this out yet but this didn't happen with 15.6.7.  The other area deals with compiling google protocol buffer files (.proto) into .cc and .h files using protoc.  I'm building all the libproto and protoc dependencies and using the add_custom_command() to do the generation of the necessary .proto files.   This has worked for a very long time.  Now the google protocol buffers I was using was version 2.6.1 with modified CMake files from version 3.0.   I have since downloaded version 3.5 of google protocol buffers which has upgraded CMake support to try out.  While I can compile the libraries and protoc as before, the generation of the .cc's and .h's is producing the error.

**Comment by brettadams53** [comment]
lukka,  while I do both Windows and Linux configuration this way it's the Windows route that has been causing me problems.   I was going to report on it when I came across the VSLinux reference to the same thing when a remote CMake of 3.11 was being used.   I want to see the permutations of 15.0 vs. 15.7 so I know what to expect.

I'm in process of collecting some more data on this issue.

You know it's interesting as I can target different flavor of linux with Open Folder and sometimes I get a crash randomly.   By this time the files are already copied over to the VM and I can compile the code manually, then debug via VS as everything is synced binary wise.   Haven't really figured out the pattern yet as I target a lot of different VM's.

I explained before what projects I am compiling.

**Comment by brettadams53** [comment]
rchiodo, that add_definition work around solved both of my problems.   Thanks for the awesome response time; back to slinging bits on windows again.   Will test out on Linux target as well.

**Comment by lukka** [comment]
@brettadams53 et all: thanks for the help and the time invested to report back useful data. The workaround is to define at least one preprocessor symbol in your CMakeLists.txt file, such as:

```add_definitions(-DFOO)```

The fix is going to be published in the next VS 2017 15.8 preview.
Thanks you all a lot for the report!

**Comment by lukka** [comment]
Fix is pending release for next Preview of VS 2017 15.8.

**Comment by jensreck** [comment]
sorry for the late response but i was out of office. I added your suggestion in the last line of my CMakeList.txt, but without any changes... (15.8.0 preview 1.0). Is there any way to go back to a older release of VS2017? Where I can download it?

---------------------
1. cmake version 3.10.3
2. standard build from dist
3. build with a VBox linuxkit + docker container of ubuntu core. if required i could also check a WSL build
4. build as root
5. there is a toolchain file for this target
6. https://github.com/apache/celix.git
7. yes, a small example builds without any issues
---------------------

**Comment by itodirel** [comment]
reopening to very this is not a issue

**Comment by itodirel** [comment]
This has been addressed and fixed.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
