### ISSUE TITLE
CMake: Changes of 'cmakeCommandArgs' will not recognized

### ISSUE THREAD

**Issue by jensreck** [Microsoft/VSLinux#291]
Changes of 'cmakeCommandArgs' (add/remove arguments) will not recognized, manually deleting of CMakeCache.txt on remote Linux machine is required.

**Comment by lukka** [comment]
@jensreck could you please provide a use case in order to reproduce the issue?
Which version of Visual Studio are you using?

Note that the CMakeSettigns.json file is watched for changes, and each time you change the file the CMake configuration process should start as soon as you save it. You could control this behavior under Tools->Options->CMake->General. When 'Never run configure step automatically' is selected, you need to start the configuration process of CMake manually from CMake->Cache->Generate->ProjectName.

**Comment by jensreck** [comment]
If I add an option "-Dfoo=1" to "cmakeCommandArgs" this option will be found in the "CMakeCache.txt" file... well done.
But if I later delete this option it will be further found in the "CMakeCache.txt". Also if I trigger "Generate cache" this option will be further exist there... and... strange behaviour if I now add an additional option "-Dfoo2=3", both options are there...
Only if I delete the "CMakeCache.txt" file the option "-Dfoo=1" will be removed (and "-Dfoo2=3" is still there if I didn't removed it from the argument list).

**Comment by jensreck** [comment]
Thank you, that explains the behavior
