### ISSUE TITLE
gdb failed

### ISSUE THREAD

**Issue by Harvey-Liu** [Microsoft/VSLinux#30]
#include <iostream>
int main(void) {
	std::cout << "HelloWorld" << std::endl;
	printf("HelloWorld");
	return 0;
}

when i run remote gdb debugger i got this

=thread-group-added,id="i1"
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-pc-mingw32 --target=x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Loaded 'shared libraries loaded at this time.'
Stopped due to shared library event:
  Inferior loaded /usr/lib64/libstdc++.so.6
    /lib64/libm.so.6
    /lib64/libgcc_s.so.1
    /lib64/libc.so.6
    /lib64/ld-linux-x86-64.so.2
Loaded '/usr/lib64/libstdc++.so.6'
Loaded '/lib64/libm.so.6'
Loaded '/lib64/libgcc_s.so.1'
Loaded '/lib64/libc.so.6'
Loaded '/lib64/ld-linux-x86-64.so.2'
[Inferior 1 (process 44287) exited normally]
程序“”已退出，返回值为 0 (0x0)。

**Comment by robotdad** [comment]
Which version of the extension are you using? This should be under help, about, Visual C++ for Linux. The current version is 1.0.5. If the entry is there you are on an 1.0.3 or older and should try upgrading first.

@paulmaybee I see a stop due to shared libraries here. Thoughts?

**Comment by itodirel** [comment]
Also, are you running in gdb or gdbserver mode?

**Comment by charint0** [comment]
Same problem. 
My Visual C++ for Linux Development version is 1.0.5. 
When I start the debugger I see:

=thread-group-added,id="i1"
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-pc-mingw32 --target=x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Loaded 'shared libraries loaded at this time.'
Stopped due to shared library event:
  Inferior loaded /lib64/libstdc++.so.6
    /lib64/libm.so.6
    /lib64/libgcc_s.so.1
    /lib64/libc.so.6
    /lib64/ld-linux-x86-64.so.2
Loaded '/lib64/libstdc++.so.6'
Loaded '/lib64/libm.so.6'
Loaded '/lib64/libgcc_s.so.1'
Loaded '/lib64/libc.so.6'
Loaded '/lib64/ld-linux-x86-64.so.2'
[Inferior 1 (process 3387) exited normally]
The program '' has exited with code 0 (0x0).

**Comment by robotdad** [comment]
@Harvey-Liu have you tried again with 1.0.5 and the Linux Console Window active?

**Comment by Harvey-Liu** [comment]
@robotdad  Yes 1.0.5  is worked . I can set a breakpoint and debug, Maybe is my project settings mistake. Thankyou robotdad

**Comment by shlublu** [comment]
Hi everyone. Same issue here, with the version 1.0.7 of the extension.
The remote debugging actually works: the Linux Console Window shows me valid results. But I can set breakpoints, they are ignored.
Any idea?
Thanks a lot!
