### ISSUE TITLE
Remote Headers Intellisense

### ISSUE THREAD

**Issue by dimsedane** [microsoft/VSLinux#310]
I am  playing around with GTK on a raspberry pi. I have installed the gtkmm dev library on the device and the code in the screenshot does work, but Intellisense does not, despite having downloaded the headers:

![billede](https://user-images.githubusercontent.com/617529/42821068-02cc1b06-89d8-11e8-905d-e7ed71e1b78b.png)

I have previously had issues with the fact that my user folder contains a space. Is that an issue with the remote header feature since it does use the AppLocal folder?

I am on Visual Studio 15.7.5

**Comment by itodirel** [comment]
Could you tell me where is the location of gtkmm.h? And if you click Explore, in the UI, is the header there?

**Comment by dimsedane** [comment]
Yes, the header is at usr\include\glibmm-2.4

And it is there when using the Explore button. 

To include it at build/link time, I use `pkg-config gtkmm-3.0 --cflags --libs` is there additional project setup needed for intellisense?

**Comment by martinky** [comment]
I have the same issue on VS 15.8.2 with Qt headers.

The Qt headers were successfully copied from the remote machine to the local HeaderCache, which I verified by looking into the cache directory. For example, the `QCoreApplication` header clearly exists in this directory on my machine: `C:\Users\Martin\AppData\Local\Microsoft\Linux\HeaderCache\1.0\-1055062414\usr\include\arm-linux-gnueabihf\qt5\QtCore`. But intellisense cannot find it and if I try to open the header file from within the code editor, the following error message is displayed.
![qt_includes_intellisense](https://user-images.githubusercontent.com/1938255/45105588-e1d44200-b134-11e8-8e37-85367a96a6c8.png)

Please note, how the original include path (on the remote device) is shown, but the include path from the local cache is somehow omitted. Could it be a problem when the path is too long? For example, notice how the <opencv2/opencv.hpp> headers are correctly found - these are not as deep in the include cache directory tree.

**Comment by itodirel** [comment]
I think we now have support for doing this, let me try it and write something up

**Comment by JomaCorpFX** [comment]
Taken from https://developercommunity.visualstudio.com/content/problem/300362/linux-cmake-intellisense-headercache-not-downloadi.html

Since 'rsync' doesn't work for me, I found out you can revert to the previous .zip via sftp method by:

**1.** Select your connection
Update from Tools->Options->Cross Platform->Connection Manager->Remote Headers Intellisense Manager. 
Next click on Explore button.

![image](https://user-images.githubusercontent.com/18097869/53700308-efeedc80-3dbe-11e9-9716-25373e4cc5de.png)

**2.** C:\Users\[YourUser]\AppData\Local\Microsoft\Linux\HeaderCache\1.0\[IdNumber]
Rename the HeaderCache settings.xml.unused file to settings.xml

![image](https://user-images.githubusercontent.com/18097869/53700336-1876d680-3dbf-11e9-984b-6f08918602cb.png)

**3.** In the settings.xml file Change the syncMethod to sftp_ssh.

![image](https://user-images.githubusercontent.com/18097869/53700350-36443b80-3dbf-11e9-83fe-d075ddc3b7b3.png)

**4.** Update headers cache from Tools->Options->Cross Platform->Connection Manager->Remote Headers Intellisense Manager.
**5.** Enjoy.
Before 
![image](https://user-images.githubusercontent.com/18097869/53700392-d1d5ac00-3dbf-11e9-8bf6-70d6bf4b4cbd.png)

![image](https://user-images.githubusercontent.com/18097869/53700406-08abc200-3dc0-11e9-8a03-69b6018fda08.png)

After
![image](https://user-images.githubusercontent.com/18097869/53700357-5d027200-3dbf-11e9-8d6f-a5ecd1a17ace.png)

![image](https://user-images.githubusercontent.com/18097869/53700427-401a6e80-3dc0-11e9-93fd-22589925db05.png)

**Comment by itodirel** [comment]
I validated these scenarios, and I believe these issues have all been addressed and these scenarios work well. If you have any issues, please open a ticket on the Developer Community. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
