### ISSUE TITLE
How to configure different build and debug machines?

### ISSUE THREAD

**Issue by AliAskari** [microsoft/VSLinux#313]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

I am building my project on machine A, but I'm trying to debug it on machine B. in `launch.vs.json`  of the project I am using machine's B name under the `remoteMachineName` section but I am getting the following error:

![image](https://user-images.githubusercontent.com/4864412/43156359-e74eae50-8f47-11e8-8d55-b449cde0204b.png)

* Expected results

Be able to lunch the debugger on a different machine.

* Actual results (with build output window contents if applicable)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

VC++ : 15.7.5
OS: RedHat 7.3
gcc: 4.8.5
gdb/gdbserver: 7.6.1-94.el7

* Steps required to reproduce the error

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by paulmaybee** [comment]
the -environment-cd command is passed the value from the "cwd" property in your launch.vs.json file. Normally it looks something like: "cwd": "${debugInfo.remoteWorkspaceRoot}"
If you are not debugging on the build machine (A) then you will need to change "cwd" to reference a valid location on machine B. Also you will need to manually copy your output binary to machine B and make sure "program" references it in the correct location.

**Comment by AliAskari** [comment]
> Also you will need to manually copy your output binary to machine B and make sure "program" references it in the correct location.

Yeah, this I understand and I have already set my postbuild to do it for me. 

> Normally it looks something like: "cwd": "${debugInfo.remoteWorkspaceRoot}"

Yeah, that was it. I manually changed `"cwd"` to point to the right path and it's now working without any issues. Thanks!

**Comment by martinkalkhofer** [comment]
What I miss is the possibility to do the copy job to B with a task in tasks.vs.json which can be referenced from the launch.json as a "prelaunch task". Copying with a postbuild step would lead to a build error if debug machine is not running.

I know that VSCode has this feature. It would be important to have something similar in Visual Studio.

**Comment by itodirel** [comment]
Regarding the original ask, we support that naively: https://devblogs.microsoft.com/cppblog/linux-development-with-c-in-visual-studio-2019-wsl-asan-for-linux-separation-of-build-and-debug/. For any other requests please open separate suggestions on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
