### ISSUE TITLE
How can I use third-party SDK when developing?

### ISSUE THREAD

**Issue by deximy** [microsoft/VSLinux#315]
I'm trying to write a project with a third-party SDK. It's a cross platform project.
On windows, what I need to do is just set Additional Include Directoris in C/C++ and Additional Dependencies in Linker and it works fine.
However, when I tried to transform the project to Linux and set AID and AD to compile, VS told me error " No such file or directory" on the line of the "#include".
Wouldn't VS copy the dependencies to the remote machine automatically? If not, what should I do to compile the project? Where should I copy the SDK to manually? Or are there any document can I refer to?
Thanks a lot!

**Comment by itodirel** [comment]
Additional Include Directories, takes both a local Windows path, for IntelliSense, and a remote (absolute) path, for the build. IntelliSense runs on Windows, locally. Build runs remotely, on the Linux machine. Regarding the absolute paths, we are planning on addressing it and tracking with #68 

If you have any other comments or issues, please open a ticket or suggestion, on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
