### ISSUE TITLE
Visual Studio freezes when Locals and Autos windows are open

### ISSUE THREAD

**Issue by AliAskari** [microsoft/VSLinux#329]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

If the scope of the debugger changes to a file with a significant number of locals, the locals and autos debug windows do not update and Visual Studio just freezes and doesn't show the variables in the locals and autos windows. I remember having this issue 2 years ago and I think the source of the problem was in the MIEngine, and it got resolved. It's back again, I can track it back until version 15.7 but don't have any older installations to test.

Closing the debug windows fixes the issue and one can continue with debugging. This should be done *before* the start of the debugging session.

* Expected results

The locals and autos debug windows should be updated in a timely manner when a big file is in the scope of the debugger.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

VC++ : 15.9.0/15.8.3
OS: RedHat 7.3
gcc: 4.8.5
gdb/gdbserver: 7.6.1

**Comment by paulmaybee** [comment]
Can you generate a gdb log file for your failure case? In the Command Window enter
`debug.midebuglog /On:some-file-name
`
Then run your repro case. Then enter
`debug.midebuglog /Off
`

**Comment by AliAskari** [comment]
@paulmaybee Visual Studio freezes when I reproduce this issue and I cannot run any commands after reproducing the issue. Is there any other way to run these commands outside of Visual Studio?

**Comment by paulmaybee** [comment]
If you kill VS when it freezes then the log file should be present and contain everything generated up until the freeze occurred.

**Comment by itodirel** [comment]
Please provide us a log so we can investigate. If you still have this issue, please open an issue on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
