### ISSUE TITLE
Include remote source file into compilation

### ISSUE THREAD

**Issue by huang-tianwen** [microsoft/VSLinux#335]
* A brief description
I am building a project which need to use dlib library, in dlib, they ask us to extract their library and add dlib/all/source.cpp to our project. (in normal windows c++ project, i just need to add existing item and add that file into my project).

http://dlib.net/compile.html
Compiling C++ Examples Without CMake
In most cases, to use this library all you have to do is extract it somewhere, make sure the folder containing the dlib folder is in your include path, and finally add dlib/all/source.cpp to your project.

* Expected results
Able to include a file in remote system

* Actual results (with build output window contents if applicable)
i found no way to do that.

* VC++ 2017, Windows Subsystem Linux

* Steps required to reproduce the error
download dlib and try to use it in project.

**Comment by itodirel** [comment]
we support remote pre build steps, you could in theory write a shell scripts that extracts the library, and run it as part of the build step, but you'll have to do your own incremental support, let me know if that is something you're willing to try and we can provide more details

**Comment by itodirel** [comment]
This isn't a CMake question correct? For CMake, just include the source file, as long as is on the remote, nothing else has to be done, as CMake is ran remotely. For MSBuild, simply populate RemoteClCompile items, enable debug verbosity and see for examples in the build output.

Here are two examples:

```
 RemoteClCompile=
1>            /mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/main.cpp
1>                    CommandLine=-c -x c++ /mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/main.cpp -g2 -gdwarf-2 -o "/mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/obj/x64/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11
1>                    LocalFileName=C:\Users\iontodirel\source\repos\ConsoleApplication29\ConsoleApplication29\main.cpp
1>                    LocalName=main.cpp
1>                    LocalOutputFileName=C:\Users\iontodirel\source\repos\ConsoleApplication29\ConsoleApplication29\obj\x64\Debug\main.o
1>                    OutputFileName=/mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/obj/x64/Debug/main.o
1>                    RemoteToolExe=g++
1>            /mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/Source.cpp
1>                    CommandLine=-c -x c++ /mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/Source.cpp -g2 -gdwarf-2 -o "/mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/obj/x64/Debug/Source.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11
1>                    LocalFileName=C:\Users\iontodirel\source\repos\ConsoleApplication29\ConsoleApplication29\Source.cpp
1>                    LocalName=Source.cpp
1>                    LocalOutputFileName=C:\Users\iontodirel\source\repos\ConsoleApplication29\ConsoleApplication29\obj\x64\Debug\Source.o
1>                    OutputFileName=/mnt/c/Users/iontodirel/source/repos/ConsoleApplication29/ConsoleApplication29/obj/x64/Debug/Source.o
1>                    RemoteToolExe=g++
```

For any other questions, please open a ticket on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
