### ISSUE TITLE
Preprocessor Definitions in Linked static library not working

### ISSUE THREAD

**Issue by huang-tianwen** [microsoft/VSLinux#337]
Please use the following bug reporting template to help produce actionable and reproducible issues:

main.cpp
`#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>
#include <dlib/image_io.h>
#include <dlib/opencv/to_open_cv.h>
#include <dlib/opencv/cv_image.h>

#include <cstdio>

using namespace dlib;
using namespace cv;
using namespace std;

int main(int argc, char **argv)
{
	array2d<rgb_pixel> img;
	load_image(img, argv[1]);
}`

Property Sheet
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <IncludePath>D:\dlib-19.15\dlib-19.15;$(IncludePath)</IncludePath>
    <AdditionalSourcesToCopyMapping>
    </AdditionalSourcesToCopyMapping>
    <ProjectPublicIncludePath>
    </ProjectPublicIncludePath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>/home/andi/dlib-19.15;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>DLIB_JPEG_SUPPORT;DLIB_PNG_SUPPORT</PreprocessorDefinitions>
      <ForcedIncludeFiles>
      </ForcedIncludeFiles>
      <AdditionalOptions>
      </AdditionalOptions>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>/home/andi/dlib-19.15/examples/build_debug/dlib_build;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
    <Link>
      <AdditionalDependencies>-ljpeg;-lpng;-ldlib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>`

* Expected results
Compiled with DLIB_JPEG_SUPPORT

* Actual results (with build output window contents if applicable)
Error when running application
"terminate called after throwing an instance of 'dlib::image_load_error'
  what():  Unable to load image in file ...
You must #define DLIB_JPEG_SUPPORT and link to libjpeg to read JPEG files.
Do this by following the instructions at http://dlib.net/compile.html.

Note that you must cause DLIB_JPEG_SUPPORT to be defined for your entire project.
So don't #define it in one file. Instead, use a compiler switch like -DDLIB_JPEG_SUPPORT
so it takes effect for your entire application."

* Visual Studio 2017 15.8.3, Windows Subsytem, GCC/GDB/gdbserver version, 64-bit, etc.

* Steps required to reproduce the error
-Install dlib in windows subsystem linux.(http://dlib.net/compile.html)
-Create a new Linux Console Application
-Use my code above for main.cpp.
-Run the application with input jpeg file.

Tried to compile in Subsystem with this command
g++ -std=c++11 -O3 -I/usr/local/opencv/debug/include -I/home/andi/dlib-19.15 -DDLIB_JPEG_SUPPORT -DDLIB_PNG_SUPPORT test.cpp -lpthread -lX11 -ldlib -lopencv_calib3d -lopencv_core -lopencv_dnn -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videoio -lopencv_video -lopencv_videostab -ljpeg -lpng -L/usr/local/opencv/debug/lib -L/home/andi/dlib-19.15/examples/build_debug/dlib_build

the result can load jpeg file

**Comment by itodirel** [comment]
Hi, can you share your project?

**Comment by itodirel** [comment]
Hi, we believe this scenario works and it's a misconfiguration in the project. Please share a repro or the diagnostic log and attach it to a issue on the Developer Community. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
