### ISSUE TITLE
ResolveRemoteDir fails incorrectly

### ISSUE THREAD

**Issue by mqudsi** [microsoft/VSLinux#338]
Using Visual Studio 15.9.0 Preview 2 connecting to a Debian 9.3 (stretch) host over ssh with private key authentication, I'm able to connect to the remote host OK (except for #306), however upon attempting to debug the `ResolveRemoteDir` step fails with error 

> Could not resolve path `~/projects/fish', readlink exit code: 1

The directory exists:

```fish
~> readlink -f ~/projects/fish; echo $status
/home/mqudsi/projects/fish
0
```

I have tried using an absolute path instead, but the result is the same.

Is #306 responsible for this as well?

**Comment by itodirel** [comment]
no, I don't think that is related, we are investigating

**Comment by itodirel** [comment]
@elizabethmorrow can you take a look?

**Comment by itodirel** [comment]
We believe this issue has been addressed. If you still see an issue here, please give us the log, and provide the information in a issue ticket on the Developer Community. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
