### ISSUE TITLE
rsync can't handle WSL symlinks

### ISSUE THREAD

**Issue by mqudsi** [microsoft/VSLinux#343]
In my source directory is a symlink'd directory created from within WSL. When VSLinux executes its rsync port, it barfs when attempting to synchronize that path with the following error:

> ...
> test/is_potential_path_test/beta/
> tests/
> rsync: send_files failed to open "/C/Users/mqudsi/random/fish-shell/test/home/fish/functions": Bad file number (9)

The following debug info was obtained from within WSL:
```fish
mqudsi@ZBook /m/c/U/m/r/fish-shell> file test/home/fish/functions
test/home/fish/functions: symbolic link to /mnt/c/Users/mqudsi/random/fish-shell/tests/test_functions
```

**Comment by benmcmorran** [comment]
This issue is being closed because we are no longer tracking VS Linux issues on GitHub. If the issue still reproduces, bugs and new suggestions should be reported on the [Developer Community forum](https://developercommunity.visualstudio.com). It is centralized, better equipped for group voting, and has more visibility.
