### ISSUE TITLE
SFTP: Error occurred during copy: The session is not open. (Channel was closed.)

### ISSUE THREAD

**Issue by therealwolf42** [microsoft/VSLinux#344]
I've been trying to get VS Linux with WSL to run. But RSYNC doesn't work (getting same error as here: https://developercommunity.visualstudio.com/content/problem/277250/get-error-when-cmake-and-rsync-to-a-remote-docker.html) and the fix was to change rsync to `sftp`.

Now, this copies the data to the remote folder, but with a big project, it stops after roughly a minute. The error message changes between versions. I've tried both 15.9.0 Preview 3.0 and 15.8.6

```
1> 14:34:27: Copying files to remote machine...
1> 14:34:57: Copied 49 files out of 7895...
1> 14:35:02: Copied 97 files out of 7895...
1> 14:35:07: Copied 146 files out of 7895...
1> 14:35:12: Copied 195 files out of 7895...
1> 14:35:17: Copied 244 files out of 7895...
1> 14:35:22: Copied 293 files out of 7895...
1> 14:35:27: Copied 342 files out of 7895...
1> Error occurred during copy: Channel was closed. ({15.8.6} => Error occurred during copy: The session is not open.)

#And with verbose (in this case it copied for 2 minutes)
1> Error occurred during copy: Error occurred during copy: Timed out executing command 'basename '/var/tmp/src/f43d6681-0074-9431-9062-5c6e7c1e6222/Linux-Debug/doxygen/html/comment__object_8hpp_source.html'', waited for 16165,0145ms.
```

---

So my questions are:

1.) Is it possible to add a timeout arg for SFTP? (google didn't help)
2.) Is it necessary to copy the files to WSL every time?
3.) Is a fix available for RSYNC already?

--- 

Hope you guys can help me!

**Comment by boskars** [comment]
The solution may be here: see #208 and ssh configuration parameter: ClientAliveInterval

**Comment by therealwolf42** [comment]
@boskars 
I've changed the ClientAliveInterval on the sshd and ssh config to 0, but I still get the timeout - this time later though.

```
1> 15:18:04: Copied 3633 files out of 7895...
1> Error occurred during copy: The session is not open.
```

**Comment by ranganathanrajeshkumar** [comment]
Enable as below, It worked for me:

TCPKeepalive yes

**Comment by itodirel** [comment]
Thanks @ranganathanrajeshkumar. I this is still a issue, please provide repro steps and open an issue for us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
