### ISSUE TITLE
After some point, build hangs

### ISSUE THREAD

**Issue by mqudsi** [microsoft/VSLinux#345]
Using Visual Studio 15.9 Preview 3, after some point the VSLinux build command hangs devenv.exe, and no output is posted to the cmake, build, or debug windows. After a timeout (~10 seconds?), an error message is displayed "build failed, continue debug?" and nothing you do will get build working again.

Must `sudo killall -9 rsync` on the remote host, kill and restart `devenv.exe` locally in order to get it working again. 

Killing `rsync` remotely can induce this bug. (`rsync` does not appear to quit on the remote host after the sync is complete.)

Is there some sort environment that the peeps at MS are using that I can reproduce locally so I can get this thing to work? I've had about zero luck with VSLinux in CMake mode with a remote host over ssh.

**Comment by mqudsi** [comment]
All of my problems went away when I created a new Fedora Server 28 virtual machine as the remote build host with a copy of cmake installed from git and all other requirements (rsync, gdb, g++, gcc, etc) installed via yum.

But I both Ubuntu and Debian gave me endless problems.

**Comment by itodirel** [comment]
@lukka @elizabethmorrow can you investigate?

**Comment by elizabethmorrow** [comment]
@mqudsi 

We've made a lot of improvements to rsync in Visual Studio 2019 Update 1, are these issues still present for you? Ubuntu and Debian should both be supported scenarios.

**Comment by itodirel** [comment]
We are not able to reproduce, please provide us with a diagnostic log of the build, as well as log from our system, as documented here: https://devblogs.microsoft.com/cppblog/visual-studio-cmake-support-clang-llvm-cmake-3-14-vcpkg-and-performance-improvements/, if more information is available, please provide it on the developer community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
