### ISSUE TITLE
Adding remote FreeBSD host fails with password-based authentication

### ISSUE THREAD

**Issue by mqudsi** [microsoft/VSLinux#346]
Under Visual Studio 15.9 Preview 3, adding a 64-bit FreeBSD 11.2 host fails with password-based authentication. I can SSH into the remote host from WSL just fine.

Adding the host via private-key-based authentication works.

**Comment by itodirel** [comment]
Hi, out FreeBSD support is limited, but connecting and building should be fine

**Comment by mqudsi** [comment]
Is this a recent development? I was completely unable to get anywhere with FreeBSD. 

See also #348 and the solution I uploaded.

**Comment by itodirel** [comment]
This issue has been addressed, we can connect with no problem to FreeBSD. There are a few issues with rsync that we are investigating and will address, tracked with #348 

![image](https://user-images.githubusercontent.com/15239856/78212473-b1659e80-7464-11ea-8150-ee7152be9029.png)

For any other issues, please open a ticket on the Developer Community. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
