### ISSUE TITLE
How to avoid the errors in error list?

### ISSUE THREAD

**Issue by yutiny** [microsoft/VSLinux#354]
I create ConsoleApplication1, connect to a debian 9.5 server, also download the remote linux header by click update.
Here's the problem, how to avoid errors in error list.
![picture](http://www.yutiny.com/images/2018-10-26.jpg)

**Comment by yuehuang010** [comment]
The error are coming from IntelliSense.  You can turn it off by selecting "Build" instead of "Build+IntelliSense"

**Comment by itodirel** [comment]
for float128 fix, it requires compiler support on the IntelliSense compiler host compiler, which is MSVC; we have plans on addressing it before that in VS 2019, but not clear when yet

**Comment by itodirel** [comment]
We are tracking this issue using: https://developercommunity.visualstudio.com/content/problem/484237/wsl-float128-is-undefined.html 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
