### ISSUE TITLE
Compilation error c++ - i386 architecture of input file `/home/alessandro/projects/Inicializa/obj/x86/Debug/main.o' is incompatible with i386:x86-64 output	

### ISSUE THREAD

**Issue by alessandrofigueiredo** [microsoft/VSLinux#356]
I'm trying to use a 32 bit .so lib in my c++ application inside a 64 bit Ubuntu 18.04. 
But when I changed my application to compile in a 32 bit architecture to load the .so lib properly, 
I get several errors when a try to compile the application in visual studio. 
I've already changed my linux config according the issue #25 and set the flag -m32 in command line arguments with no sucess results.

**Comment by paulmaybee** [comment]
What are the errors you are getting? Do you have a log?

**Comment by alessandrofigueiredo** [comment]
I'm getting two errors:
1 - E1696 - Severity	 Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "gnu/stubs-32.h"	Inicializa	C:\Users\alessandrofigueiredo\AppData\Local\Microsoft\Linux\HeaderCache\1.0\177825111\usr\include\x86_64-linux-gnu\gnu\stubs.h, Idon't know why is searching in my local machine.
	
2 - The one that was in the title of this issue, about incompatible main.o file output, but I put -m32 in the linker command line and the problem was solved.

**Comment by itodirel** [comment]
We believe the IntelliSense issue is addressed. The other issue is coming from the compiler, it's possible the .so library is not compiled properly, and it's an authoring problem. If you still have an issue, please open it on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
