### ISSUE TITLE
"CMake 3.8.x or above is not available", though it is

### ISSUE THREAD

**Issue by nunoplopes** [Microsoft/VSLinux#358]
(I can't reopen #351, so opening a new bug report, since there *is* a bug here)

I'm using VS 15.8.7 cmake open folder + Linux remote build.
However it is not working and I get the error: "Error occurred during copy: CMake 3.8.x or above is not available on the remote system".

Logging in on the remote server, /var/log/secure shows the login being successful:
```
Oct 14 10:46:01 sshd[129065]: Accepted publickey for nuno from xx.xx.xx.xx port xx ssh2: RSA foo
Oct 14 10:46:02 sshd[129065]: pam_unix(sshd:session): session opened for user nuno by (uid=0)
Oct 14 10:46:02 sshd[129086]: Received disconnect from xx.xx.xx.xx port xx:11: Connection terminated by the client.
Oct 14 10:46:02 sshd[129086]: Disconnected from xx.xx.xx.xx port xx
Oct 14 10:46:02 sshd[129065]: pam_unix(sshd:session): session closed for user nuno
```

The CMakeSettings.json file has the following line:
"cmakeExecutable": "/usr/bin/cmake",

and running that on the maching:
```
$ /usr/bin/cmake --version
cmake3 version 3.12.1
```
So this is more recent than the required 3.8.
I'm sure this CMakeSettings.json file is being picked up because I see the output changing depending on the value of "remoteCopySourcesOutputVerbosity".
I've opened the "Linux Console Window", but it shows no output.

At this point I'm unable to debug the issue any further. I don't know which command VS is executing (if any, since I don't see anything in ~/.bash_history).

Is cmake open folder + remote build supported?  The remote server has CentOS 7 (Azure VM).

**Comment by lukka** [comment]
@nunoplopes the problem is that our cmake identification version fails because the output of cmake says "cmake**3**", while we expect it to be just "cmake" (no trailing 3).
We could certainly fix that on a future version of VS.

As a workaround, please install this [cmake package](https://github.com/Microsoft/CMake/releases/tag/untagged-fb9b4dd1072bc49c0ba9), or grab the cmake source and build it on the target machine. In both cases the version check would not fail.

**Comment by itodirel** [comment]
This issue should be now fixed, if this is still an issue for you, please open a issue on the Developer Community
