### ISSUE TITLE
How to build a library with dependent library?

### ISSUE THREAD

**Issue by pvanoppen2** [microsoft/VSLinux#362]
I have a Linux project set up that builds a static library: libcompat.a which holds (among others) setproctitle.o
A second Linux library (libcommon-daemon-lib) should include some new objects files (log.o and ctl.o) and the complete content of the generated libcompat.a 

Using ar it would look something like :
`ar cr .libs/libcommon-daemon-lib.a log.o ctl.o  .libs/libcompat.a/setproctitle.o ... `

In Visual Studio I could create libcommon-daemon-lib.a just by listing out the source files, but that means that setproctitle is compiled twice, which is not efficient.
When I add a reference in libcommon-daemon-lib to libcompat,  the dependent lib is build first (great) but is there an elegant way to get the content into the new library?

If this can only be done with a Remote Post Build process step, how do I reference the remote output directory of the libcompat project? For the current project that would be $(RemoteOutDir)$(TargetName), but is there a way to access the properties of another project in the same solution, something like: $(libcompat.RemoteOutDir)$(libcompat.TargetName)  ?

Using Visual Studio version 15.9.5, compiling for Ubuntu 16.04LTS x64

**Comment by pvanoppen2** [comment]
It appears that references to Linux targets have a problem. When I add a reference to a library it claims a Microsoft.VisualStudio.ProjectSystem.References.UnresolvedBuildDependencyProjectReference" reference could not be resolved. , even though the library builds successful on the remote target.
![image](https://user-images.githubusercontent.com/36933398/51769074-e1fabd00-2096-11e9-8a96-a43e5ac2f660.png)

**Comment by pvanoppen2** [comment]
This issue was presumable fixed some time ago, but appears in my 15.9.5 Version of Visual Studio.
[https://developercommunity.visualstudio.com/content/problem/196761/linux-c-project-doesnt-allow-to-specify-path-to-a.html](url)

**Comment by yuehuang010** [comment]
I am not able to repro the issue.  Could you share your sample?
![image](https://user-images.githubusercontent.com/19828377/51781144-8f86c400-20c9-11e9-8d23-bac3362b4245.png)

**Comment by pvanoppen2** [comment]
I created a libA, that generates a static library (liblibA.a), leaving most settings as default.
Next a sandbox project (also with most settings left as default) with a simple main() is able to include (and use) the method declared in the references libA. 
However the liblldpctl project, which tries to include the same libA, indicates a warning sign at the library  
Reference. 
![image](https://user-images.githubusercontent.com/36933398/52003319-05e44700-2479-11e9-8f76-731c16baa18e.png)

It must be some project setting of liblldpctl that must prevent the inclusion of libA.

**Comment by pvanoppen2** [comment]
To be more specific,  the reason that you could not reproduce the issue was that you included the library into an **application**... The question however was, how to include a (static) library into a **library**.
So in stead of your console application, create a libConsole project and set the Configuration Type to **Static library (.a)** . I did that for libSandbox (see picture) and you can see the warning sign when referencing LibA
![image](https://user-images.githubusercontent.com/36933398/52018181-5e7a0b00-249e-11e9-90b6-b500bc14904f.png)

The expected behavior is that the object files created for the primary library (libA) are included in the secondary library (libSandbox).

**Comment by pvanoppen2** [comment]
Well, the work around is, to duplicate the source files of the nested library, which is not as elegant.  Are nested libraries supposed to work, or is it a feature that just is not supported?
In other words, I could not create a Sandbox Application that includes/ references libSandbox.

If it is a bug (then it should be possible to create a static library with a reference to another library), could you post a link to the issue so I can see when it is addressed. 
If it is a a non supported feature we can close this topic.

**Comment by itodirel** [comment]
Libraries consume the %(Link) item group, and archives consume the %(Lib) item group, in theory you could consume the .a directly without having to rebuild the library, @yuehuang010 would that work?

**Comment by artem-korolev** [comment]
Hi, here is example - https://github.com/artem-korolev/visual-studio-issues.git

There are 4 projects. Two under "**Main**", and two under "**Tests**"

"**test-server**" and "test-client" from Tests have reference to "**ApiCppStatic**" project. If you double click "ApiCppStatic" from "References" tree node, then it opens Object Browser.

"**Services**" project from Main section also references "**ApiCppStatic**". But if you double click on this reference, then it shows "The "**Microsoft.VisualStudio.ProjectSystem.References.UnresolvedBuildDependencyProjectReference" reference could not be resolved**." message. In properties window it is also same message instead of Full Path



Well. I want to notice one more thing. project I post here is already modified and don't have real code already. But there was a code, which was working. Reference to static library was broken in UI interface, but build was successful and executable was fully working using this static library.

So I want to say, that this is only UI interface issue. The actual build is fully working. I hope it will be fixed anyways, cause such issues confuse a lot

I use WIndows. But It seems to me the same issue. Hopefully it will be fixed in both version at once :)

Best regards,
Artem

**Comment by artem-korolev** [comment]
Well.  I found solution for my particular problem
[https://imgur.com/5sLzYzA](https://imgur.com/5sLzYzA)

**Comment by itodirel** [comment]
Tracking using #363
