### ISSUE TITLE
Visual studio integration question

### ISSUE THREAD

**Issue by orioha** [microsoft/VSLinux#368]
Using open folder in vs2017 having launch.vs.json

Not using cmake . Just trying something simple

debugInfo.remoteMachineId is translated to the /s parameter in shellexec.exe

How can i know what number to choose?

Writing the hostname doesnot work

Linux cross compiler settings are set

**Comment by orioha** [comment]
I think the Problem is shellexec /s translated to a string (hostname) instead of a number

**Comment by itodirel** [comment]
The id is an identifier for the connection and is calculated with something like this:

```
string representation = HostNameOrAddress.ToLowerInvariant() + Port.ToString() + UserName + AuthenticationMode.ToString().ToLowerInvariant();
unchecked
{
     int id = 23;
     foreach (char c in representation)
     {
         id = id * 31 + c;
      }
     return id;
 }
```

You can use it to calculate your own id, the ids are stored in C:\Users\<user>\AppData\Local\Microsoft\Linux\User Data\3.0\store.xml

**Comment by orioha** [comment]
Thanks.

Entering this id manually  in the json file make the connection works.

But why isnt it auto configured based on hostname . Same on latests visual
2019 preview.

בתאריך יום ה׳, 21 במרץ 2019, 07:32, מאת Ion Todirel ‏<
notifications@github.com>:

**Comment by itodirel** [comment]
this is a bug or a spec bug, honestly your scenario is completely valid as a way to attach and debug, and should work, I will copy it as a feature on our backlog, but there might be an easier fix

**Comment by codeConcussion** [comment]
@itodirel - Thanks for the snippet - works great to generate the ids needed in store.xml.

Any idea what code is used to generate the "hash" attribute of the <store> node? I'm trying to create SSH connections programmatically rather than having to use Visual Studio.

**Comment by itodirel** [comment]
hey @codeConcussion, since then we have added programmatic access to the store, which anyone can use https://devblogs.microsoft.com/cppblog/cmake-linux-targeting-and-intellisense-improvements-in-visual-studio-2019-version-16-5-preview-2/#command

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
