### ISSUE TITLE
Includes from NuGet package not copied to remote system

### ISSUE THREAD

**Issue by Sam13** [microsoft/VSLinux#370]
I have a NuGet package which contains additional include files which I want to use during cross compilation.

The package has the following simple structure:
_build\native\include\myheader.h_
_build\native\MyPackage.targets_

MyPackage.targets:
```<?xml version="1.0" encoding="utf-8"?>
<Project ToolVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <ItemDefinitionGroup>
    <ClCompile>
       <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)include\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <ResourceCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)include\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ResourceCompile>
  </ItemDefinitionGroup>
</Project>
```

The package works fine on any C++ project which is not cross compiled.

When I try to reference the header in a cross compilation project the following compilation error occurs:
_1>D:\Project\mysource.cpp(5,10): error : myinclude.h: No such file or directory
1>D:\Project\mysource.cpp(5,10): error :  #include "myinclude.h"_

As far as I have investigated that the include files from the NuGet package are not copied to the remote system...

How can this be achieved?

**Comment by itodirel** [comment]
We don't support NuGet directly, if you want to use NuGet, the only way to do that today is to copy each file individually, we don't currently support directory copy, but plan to. Additionally, this is not going to be efficient as today we don't do that incrementally, but plan to, sooner than later. I don't recommend using NuGet for this, and using vcpkg or handle this copy externally instead using rsync. But, you can set this, as an example:

<AdditionalSourcesToCopyMapping>c:\foo.txt:=/foo.txt</AdditionalSourcesToCopyMapping>

Create a new target, and run it before _ConsolidateSourcesToCopy or _CopySources, then make it consume your directory and use it to populate AdditionalSourcesToCopyMapping

**Comment by itodirel** [comment]
As mentioned below, we believe a project can be configured to support this scenario, but we don't plan on supporting it first class at this time. If this is important to you, please open a suggestion on the Developer Community, and based on votes and demand we can revisit this scenario.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
