### ISSUE TITLE
cmake  protobuf_generate_cpp 

### ISSUE THREAD

**Issue by chee1986** [microsoft/VSLinux#371]
I add protobuf_generate_cpp to CMakeLists.txt ,the files generated in include_directories(${CMAKE_CURRENT_BINARY_DIR}),but the intellisense cannot find its,please tell me how to solve the problem

**Comment by itodirel** [comment]
This was fixed and works now with no issues. Please use latest update of VS. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
