### ISSUE TITLE
Enable run as sudo

### ISSUE THREAD

**Issue by robotdad** [Microsoft/VSLinux#39]
As the tile says. The workaround today is logon as root which obviously isn't idea.

**Comment by sourabharvikar3** [comment]
When this feature will be available.

Thanks

**Comment by AlexeyVT** [comment]
I uses Makefile project and this string before run in the Debug menu. GUID value I got from .bash_history.
sudo gdb --interpreter=mi; echo fab7778d-5eaf-46cb-943a-0a73f185bbe2; logout

And I agree. This feature should be available

**Comment by robotdad** [comment]
This one is further down on our backlog, I can say it is not going to make the next release. I'll tag this when we get it listed against a release with some confidence.

**Comment by robiwano** [comment]
+1 , I'm using the GPU on the Raspberry Pi with QPULib which needs root permission to used mailboxes and shared memory.

**Comment by tvkit** [comment]
Frustrating this trivial addition isn't available especially after two years  

Why not just post the source code for the extension so the community can pick up where MS left off.

**Comment by lukka** [comment]
@tvkit please create the two suggestions on [Developer Community forum](https://developercommunity.visualstudio.com/), thanks for your feedback.

**Comment by tvkit** [comment]
Thanks for the reply, @lukka, but I'm not gonna waste my time with Microsoft's antiquated support paradigm.  If the issues raised here are ignored by Microsoft's product managers then why does this repo exist?

Anyway, here's a way to get around the neglected deficiency...

Given the $PATH:  (_a raspian target_)

`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
`

create a shim named _gdb_ that runs _sudo_:
```
#!/bin/bash
sudo --preserve-env /usr/bin/gdb "$@"
```
and make it executable: (_in my case_)

`sudo chmod ugo+x /usr/local/bin/gdb
`

Make sure the $PATH location of the shim  precedes the location of the actual `gdb `binary; otherwise, the real `gdb `will be called first.

BTW, without the `--preserve-env` option, the home directory (~) was _root_.   In my case, the source and compiled binaries don't live @ _root_ since I setup VSLinux to shell as a different user.

To avoid polluting my shell history in the target, I created an ordinary account for build & debug.  VSLinux is configured to use this account ultimately requiring the aforementioned `--preserve-env` option,

**Comment by itodirel** [comment]
we are not planning to get to this soon, closing and copying the work item to internal database, we'll update this when done, as a workaround you can login as root

**Comment by EdwardHague** [comment]
For a Raspberry Pi, this worked perfectly for me (enabling root user on Pi): https://medium.com/@sean_t_king/how-to-log-in-as-root-user-raspberry-pi-server-b32a22f3c636

**Comment by JenoBoka** [comment]
Any update on this?
