### ISSUE TITLE
Fails to link boost (please help with project properties)

### ISSUE THREAD

**Issue by charint0** [Microsoft/VSLinux#44]
Probably this is not a bug but a simple configuration error, if so I apologize (I am new to compile under Linux). 
Anyway, I am trying to link statically the boost library to my Console project (Linux) . The project builds but fails to link (and the error is not clear to me):

1>------ Rebuild All started: Project: TestApp2, Configuration: Debug x64 ------
1>  Cleaning remote project directory
1>  Validating architecture
1>  Validating sources
1>  Copying sources remotely
1>  Starting remote build
1>  Compiling sources:
1>  main.cpp
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): warning : GMP header version 5.1.1 differs from library version 6.0.0.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(245,5): warning : GMP header version 5.1.1 differs from library version 6.0.0.
1>  Linking objects
1>collect2 : error : ld returned 1 exit status

Here is my scenario:
Microsoft Visual Studio Professional 2015 Version 14.0.25421.01 Update 3 Visual C++ for Linux Development 1.0.5
connet to virtual machine running CentOS:
Linux 3.10.0-327.el7.x86_64   #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

I tested a simple Console Application for Linux and everything was fine. Then I tried to link statically to boost. I installed with command: yum instal boost-devel
This installed boost version 1.53: I can see the headers files in /usr/include/ and the lib in  /usr/lib64/ 

Therefore I added a simple include (#include <boost/filesystem.hpp>) in my console application.
I added the configuration settings:

C/C++ -> General -> Additional Include DIrectories =/usr/include/
Linker -> General -> Additional Library Directories=/usr/lib64/
Linker -> Input -> Library Dependencies=boost

not really sure about the last setting...

(I checked that the file filesystem.hpp exists and I see: 
libboost_filesystem-mt.so
libboost_filesystem-mt.so.1.53.0
libboost_filesystem.so
libboost_filesystem.so.1.53.0
in the /usr/lib64 directory)

Probably there is more to do or the warnings I see are important. I hope someone can point me in the right direction. 

Thanks a lot.
cr

**Comment by stanthomas** [comment]
This is a general question of linking against Boost on Linux. And I recommend you run a simple Boost sample directly on the Linux system, typing in the g++ command lines, to get a feel for what's going on.

Coming to your problem, you need to individually name each Boost library that you're linking. I.e. there is no generic 'boost' library. So Linker / Input / Library Dependencies will be: `boost_filesystem` (`boost_filesystem-mt` is the multi-threaded version of the library which I'll guess you're not using here).

There's no need to specify `/usr/lib64/` in Additional Library Directories because it is automatically searched.

Incidentally, you're not statically linking to Boost::filesystem 'cos you're using the shared libraries (.so). Static libraries have extension .a. Yes you can link statically but that's a question ~~Google~~ Bing and StackOverflow can answer for you.

You can see linker errors in the output by increasing the verbosity, see [Visual C++ for Linux Development ](https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#verbose) for details.

**Comment by lgolding** [comment]
If you do what Stan suggests and it still doesn't work, please turn on [Verbose build output](https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#verbose) send us the output, and we'll take a look.

**Comment by charint0** [comment]
Solved, thank you guys! This is what I did:
1. I installed for real the static boost library (command: yum install boost-devel-static)
2. I changed the configuration properties to: 
Linker -> Input -> Library Dependencies :  boost_system ; boost_filesystem-mt 
(I have to add boost_system too, otherwise I get "error: undefined reference to symbol '_ZN5boost6system15system_categoryEv'")
I removed the unnecessary Linker -> Input -> Additional Library Directories

stanthomas: I will follow your advice to to practice building with g++ commands, thanks!
Something strange is that I enabled the "Enable Verbose Mode" both in C/C++ -> General and in Linker -> General but it didn't help much, the output was the same.
