### ISSUE TITLE
Linking a chain of Shared Object libraries / Position Independent Code

### ISSUE THREAD

**Issue by duncangravill** [Microsoft/VSLinux#49]
I would like to create a solution consisting of four Shared Object libraries: libA.so, which has two dependencies: libAA.so and libAB.so, which itself has a dependency: libABA.so.

To get started I'm simply attempting to link two Shared Object libraries: libA.so and libAA.so. Each library just consists of a single function. The function in libA calls the function in libAA. libAA compiles fine. 

I have added the absolute path to libAA in libA's Additional Dependencies project property. I have also added a reference to libAA to the libA project.

The command line for LibA is:

`-o"C:\Users\Duncan\OneDrive\A\A\bin\x64\Debug\libA.so.1.0" -Wl,-z,relro "/root/projects/AA/bin/x64/Debug/libAA.so.1.0" -shared -Wl,-z,noexecstack -Wl,--no-undefined -Wl,-z,now`

When I attempt to build libA I get an error:

> relocation R_X86_64_PC32 against undefined symbol `_Z11FunctionTwov' can not be used when making a shared object; recompile with -fPIC

I switched on diagnostic build output and had a look at the build command lines for both libA and libAA. I found that neither of the commands included the -fPIC switch to stipulate output of Position Independent Code. As I understand it PIC is generally recommended for Shared Objects, and it seems when linking one .so to another .so it is perhaps a requirement. 

Is there a way I can add the -fPIC switch to the build command line in the project properties? I have looked at all the properties and cannot see how to add it? If it cannot be added in project properties, can I open up the .vcxproj file and edit the XML to enable -fPIC? Otherwise is there another solution to this scenario of chaining multiple Shared Object Libraries? 

Thanks for creating this excellent extension,
Duncan

**Comment by robotdad** [comment]
I'm not in front of a PC right now... I believe under all options for both compile and link there is a spot to place additional flags. After hitting apply it should also show you how all the properties are being evaluated for the command lines generated.

**Comment by stanthomas** [comment]
You can turn on the Position Independent Code flag (-fpic) directly in the project property page for C/C++ :
[Image](https://1drv.ms/i/s!AmIJNoWIEjSf6DRhTgVP6vbKYod8)

And, as Marc (@robotdad) says, you can set any g++ option that doesn't have a direct setting in VCLinux on the Additional Options line.

**Comment by duncangravill** [comment]
@stanthomas @robotdad many thanks! My simple two library chain is building now. Need to develop and test my architecture further. I was mistakenly looking in the linker properties. I was trying to add -fPIC to the Additional Options in the linker properties and of course it wasn't showing up in the command line.

I notice that currently the -fpic option is available, which creates target-dependent code, and not the -fPIC option which creates target-independent code. It's working fine for me, and as -fpic apparently creates faster code that is great. Perhaps -fPIC might be needed on occasion though??

**Comment by stanthomas** [comment]
As I understand it, `-fpic` creates a Global Offset Table (GOT) with size limits on some platforms, but not x86; I don't know the situation on ARM. `-fPIC` creates a GOT without size limitations but it's less efficient. There is a tendency for library writers to ship makefiles with the more general `-fPIC` option however, for small libraries and on x86, `-fpic` is fine.

C++ can generate a large number of symbols, particularly when using templates (try the command: `nm -D --defined-only <your lib name>.so` to see this for yourself) and, since GCC exports all symbols by default, this can quickly fill up the GOT so there is a case for offering `-fPIC` too.

It might be appropriate to close this issue and open a new one to specifically propose adding -fPIC to the 'Position Independent Code' dropdown.
