### ISSUE TITLE
Object files are copied back

### ISSUE THREAD

**Issue by avinabmalla** [Microsoft/VSLinux#51]
After compiling each source file, Visual Studio copies the object files (*.o) back to the local computer, which slows down the build for projects with multiple source files. An option could be provided to disable this, or the copying and building could be carried out in parallel to speed up compiling process.

**Comment by stanthomas** [comment]
Presumably something with the right name and date stamp has to be on the Windows host for incremental build to work (non-makefile project). A simple option to not copy object fies back could end up making builds even slower. Perhaps it would be possible to create zero-length dummy files locally following a successful compilation.
I don't find this a big problem following the introduction of incremental building in 1.0.5, since only affected files are  copied (and I am working with VMs on the same host). But header dependencies need resolution (#29) to put it to bed :wink:

**Comment by avinabmalla** [comment]
I am currently developing for a Raspberry Pi 3 connected to the local network over WiFi, and the copying the object file back takes longer than compiling the object file. A VM on the same host would certainly be faster.

How about using something like a SQLite databases to store the name and date stamp? Incremental builds could then check the database and build the updated source files .

**Comment by stanthomas** [comment]
Here are some things you might try to improve or workaround the file transfer speed issue:

1. use an Ethernet cable to connect the Raspberry Pi rather than wireless.
2. get a personal Ethernet switch for your desk and connect your Windows PC and Pi to it.
3. use a makefile project - VCLinux won't copy the object files because it doesn't know about  them.
4. install Debian x86 in a VM and do as much of your development as possible on a fast system only moving to the Pi when you need to debug against hardware interfaces.

**Comment by dedmen** [comment]
#38 related.
Very useful would be to be able to specify the files Downloaded Like is already possible for Copy Sources using the @(SourcesToCopyRemotely) variable.
Right now it's faster for my projects to always rebuild everything and only download the final binary.

**Comment by itodirel** [comment]
The 1.0.6 version of the extension is now available on the extension gallery, and it addresses this issue

**Comment by robotdad** [comment]
This is in 1.0.6, that corresponds to VS 2017 15.2. Here is the setting.
![image](https://user-images.githubusercontent.com/1429895/27310013-1b669f30-550c-11e7-8549-df5137e6a89e.png)
